#!/usr/bin/env bash
# gen-node-constraints.sh — regenerate arena/constraints-node.txt: the
# hash-pinned cryptography closure the sovereign offline bundle enforces
# (`mt-eval node bundle` → build_offline_bundle → pip wheel --require-hashes).
#
# Hashes are wheel-identity and therefore PLATFORM + PYTHON-VERSION specific.
# Run this on (or targeting) the machine that will BUILD the offline bundle,
# then commit the result. Prints to stdout; redirect it:
#
#   arena/scripts/gen-node-constraints.sh > arena/constraints-node.txt
#
# Override the target set (defaults cover the three common sovereign-node
# platforms on CPython 3.11):
#   PYVER=3.12 PLATFORMS="manylinux2014_x86_64 macosx_11_0_arm64" \
#     arena/scripts/gen-node-constraints.sh > arena/constraints-node.txt
set -euo pipefail

PYVER="${PYVER:-3.11}"
ABI="cp${PYVER//./}"
PLATFORMS="${PLATFORMS:-manylinux2014_x86_64 manylinux2014_aarch64 macosx_11_0_arm64}"
# The cryptography closure on CPython: cryptography -> cffi -> pycparser.
SPEC=("cryptography>=42,<50" "cffi>=2.0.0" "pycparser")

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

for plat in $PLATFORMS; do
  python3 -m pip download --only-binary=:all: \
    --platform "$plat" --python-version "$PYVER" \
    --implementation cp --abi "$ABI" \
    -d "$workdir" "${SPEC[@]}" >/dev/null
done

echo "# constraints-node.txt — hash-pinned cryptography closure for the"
echo "# sovereign offline bundle. Regenerate with arena/scripts/gen-node-constraints.sh."
echo "# Target: CPython ${PYVER} on: ${PLATFORMS}"
echo "# Generated by gen-node-constraints.sh (do not hand-edit hashes)."
echo
# One stanza per distinct (name==version), all matching-wheel hashes attached.
python3 - "$workdir" <<'PY'
import sys, glob, hashlib, os, re
from collections import defaultdict

wheels = sorted(glob.glob(os.path.join(sys.argv[1], "*.whl")))
by_nv = defaultdict(set)
for w in wheels:
    name, ver = os.path.basename(w).split("-")[:2]
    name = re.sub(r"[-_.]+", "-", name).lower()
    h = hashlib.sha256(open(w, "rb").read()).hexdigest()
    by_nv[(name, ver)].add(h)

for (name, ver), hashes in sorted(by_nv.items()):
    lines = [f"{name}=={ver}"] + [f"--hash=sha256:{h}" for h in sorted(hashes)]
    print(" \\\n    ".join(lines))
    print()
PY
