#!/usr/bin/env python3
"""Seed the public board from local run reports, as submitter 'anonymous'.

Founder-only tooling for the launch runbook's §8 "seed the board" action.
Publishes locally-kept `mt-eval queue --no-publish` reports to `run_cards`
via the SERVICE ROLE — the same lane the organizer scoring node uses — so
seeding needs neither an OAuth session nor the submit-run edge function
(the public anonymous lane, which stays gated behind the audit's H1/H2
fixes and migration 050).

    export MT_EVAL_SUPABASE_SERVICE_KEY=…   # service_role key (founder only)
    python3 scripts/seed_board_anonymous.py <batch_dir>            # dry run
    python3 scripts/seed_board_anonymous.py <batch_dir> --apply    # publish

<batch_dir> is scanned recursively for `*_report.json` (the layout
`mt-eval queue` writes: eval/logs/harness/queue/NNN_<id>/…_report.json).

What it reuses — deliberately ALL of the normal publish machinery, so a
seeded row is byte-shaped like a contributor's row:
  * assemble_run_card()        (report + RunLog → run card, id, fingerprint)
  * verify_corpus_integrity()  (the pre-publish integrity gate — never skipped)
  * build_run_card_row()       (the one row-shape SSOT; trust='unverified')
  * validate_row()             (NOT NULL guard)

What it deliberately does NOT do:
  * per-entry publishing (run_card_entries) — scores-only; corpus content is
    never redistributed by the seeding lane;
  * datasets-table upserts — queue corpora are registry-registered and their
    rows already exist server-side (an unregistered dataset is reported and
    its run skipped, never half-published);
  * trust elevation — rows land 'unverified' exactly like CLI submissions;
    promotion stays with the verifier/referee.

The row id is the deterministic fingerprint UUID and the upsert uses
merge-duplicates, so re-running the script over the same batch is
idempotent.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path

# Runnable from a checkout without installation: arena/ is the parent.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mt_eval_harness import publish as pub  # noqa: E402

SERVICE_KEY_ENV = "MT_EVAL_SUPABASE_SERVICE_KEY"
SUBMITTER = "anonymous"


def build_seed_row(report_path: Path) -> dict:
    """Assemble + integrity-gate + build the run_cards row for one report.

    Raises pub.PublishIntegrityError on a gate failure and
    FileNotFoundError when the report's RunLog is missing — callers decide
    whether to skip or abort.
    """
    run_card, card_id, fingerprint_hash = pub.assemble_run_card(report_path)
    for warning in pub.verify_corpus_integrity(run_card):
        print(f"    ⚠ {warning}")
    row = pub.build_run_card_row(
        run_card,
        card_id,
        fingerprint_hash,
        submitter=SUBMITTER,
        trust="unverified",
        affirmation=(
            f"Results generated by mt-eval harness "
            f"v{run_card['harness_version']}; board-seeding publish "
            f"(launch runbook §8), recorded as '{SUBMITTER}'."
        ),
    )
    problems = pub.validate_row(row)
    if problems:
        raise ValueError(
            f"row failed validation (missing/empty: {', '.join(problems)})"
        )
    return row


def find_reports(batch_dir: Path) -> list[Path]:
    return sorted(batch_dir.rglob("*_report.json"))


def post_row(row: dict, service_key: str, timeout: int = 15) -> dict:
    """Service-role upsert of one run_cards row (merge-duplicates)."""
    req = urllib.request.Request(
        f"{pub.SUPABASE_URL}/rest/v1/run_cards",
        data=json.dumps(row).encode(),
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates,return=representation",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        body = json.loads(resp.read())
    return body[0] if isinstance(body, list) and body else body


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("batch_dir", type=Path,
                    help="Directory scanned recursively for *_report.json")
    ap.add_argument("--apply", action="store_true",
                    help="Actually publish. Default is a dry run: assemble + "
                         "validate every row, print the plan, write nothing.")
    args = ap.parse_args()

    if not args.batch_dir.is_dir():
        print(f"error: not a directory: {args.batch_dir}", file=sys.stderr)
        return 2

    reports = find_reports(args.batch_dir)
    if not reports:
        print(f"error: no *_report.json under {args.batch_dir}",
              file=sys.stderr)
        return 2

    service_key = os.environ.get(SERVICE_KEY_ENV, "")
    if args.apply and not service_key:
        print(f"error: --apply needs {SERVICE_KEY_ENV} in the environment.",
              file=sys.stderr)
        return 2

    host = pub.SUPABASE_URL
    print(f"Seeding target: {host}  (submitter '{SUBMITTER}', "
          f"trust 'unverified', scores-only)")
    print(f"Reports found:  {len(reports)} under {args.batch_dir}\n")

    rows: list[tuple[Path, dict]] = []
    skipped = 0
    total_cost = 0.0
    for rp in reports:
        rel = rp.relative_to(args.batch_dir)
        try:
            row = build_seed_row(rp)
        except pub.PublishIntegrityError as exc:
            print(f"  ✗ {rel}: INTEGRITY GATE: {exc} — skipped")
            skipped += 1
            continue
        except (FileNotFoundError, ValueError, KeyError) as exc:
            print(f"  ✗ {rel}: {exc} — skipped")
            skipped += 1
            continue
        cost = row.get("total_cost_usd") or 0.0
        total_cost += cost
        rows.append((rp, row))
        print(f"  ✓ {row['language_pair']:<10} {row['model_slug']:<38} "
              f"{row['condition']:<8} chrF++ "
              f"{row['chrf_plus_plus'] if row['chrf_plus_plus'] is not None else '—':>5} "
              f" ${cost:.4f}  id={row['id'][:8]}…")

    print(f"\n{len(rows)} row(s) ready, {skipped} skipped; "
          f"actual batch cost ${total_cost:.4f}")

    if not args.apply:
        print("\nDry run — nothing was published. Re-run with --apply.")
        return 0 if rows else 1

    published = 0
    failures = 0
    for rp, row in rows:
        try:
            result = post_row(row, service_key)
            published += 1
            print(f"  ↑ published {row['language_pair']} "
                  f"{row['model_slug']} (id={result.get('id', '?')[:8]}…)")
        except urllib.error.HTTPError as exc:
            failures += 1
            body = exc.read().decode()[:200]
            print(f"  ✗ {rp.name}: HTTP {exc.code}: {body}")
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            failures += 1
            print(f"  ✗ {rp.name}: {exc}")

    print(f"\nPublished {published}/{len(rows)} row(s)"
          + (f", {failures} failed" if failures else "") + ".")
    print("Rows are live on the leaderboard immediately; regenerate the "
          "served artifacts (generate_sweep_queue.py) to light the mesh.")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
