"""threshold_seal — Python↔seal.mjs format parity + refusal edges.

The parity fixtures under fixtures/sovereign/ were generated by seal.mjs
itself (throwaway keys, synthetic sentences): if the Python open ever
drifts from the Node seal, these tests fail — the two implementations are
pinned to ONE envelope format. SecretBuffer hygiene is covered here too.
"""

from __future__ import annotations

import base64
import json
import secrets
from pathlib import Path

import pytest

pytest.importorskip(
    "cryptography",
    reason="sovereign threshold lane needs the cryptography library "
           "(pip install 'mt-eval[node]')")

from mt_eval_harness.sovereign import threshold_seal as ts
from mt_eval_harness.sovereign.secret_buffer import SecretBuffer
from mt_eval_harness.sovereign.shamir_gf256 import combine, split

FIXTURES = Path(__file__).parent / "fixtures" / "sovereign"


def _fixture_scalar() -> bytes:
    from cryptography.hazmat.primitives import serialization
    key = json.loads((FIXTURES / "parity.key.json").read_text())
    priv = serialization.load_der_private_key(
        base64.b64decode(key["privateKeyDerB64"]), password=None)
    return priv.private_bytes(serialization.Encoding.Raw,
                              serialization.PrivateFormat.Raw,
                              serialization.NoEncryption())


# ---------------------------------------------------------------------------
# Cross-implementation parity (seal.mjs → Python).
# ---------------------------------------------------------------------------

class TestSealMjsParity:
    def test_node_sealed_artifact_opens_in_python(self):
        artifact = json.loads((FIXTURES / "parity.sealed.json").read_text())
        want = (FIXTURES / "parity.plaintext.json").read_text().rstrip("\n")
        got = ts.open_sealed(artifact, _fixture_scalar()).decode("utf-8")
        assert got == want

    def test_key_id_recipe_matches(self):
        key = json.loads((FIXTURES / "parity.key.json").read_text())
        der = base64.b64decode(key["publicKeyDerB64"])
        assert ts.key_id_for_spki_der(der) == key["keyId"]

    def test_node_signature_verifies_in_python(self):
        payload = (FIXTURES / "parity.sign-payload.json").read_bytes()
        sig = json.loads((FIXTURES / "parity.sig.json").read_text())
        pub = json.loads((FIXTURES / "parity.sign.pub.json").read_text())
        assert sig["scheme"] == ts.SIGN_SCHEME
        assert ts.verify_payload(payload, sig["signatureB64"],
                                 base64.b64decode(pub["publicKeyDerB64"]))

    def test_shamir_split_scalar_still_opens_node_artifact(self):
        """The custody upgrade in one assertion: split the fixture's private
        scalar 3-of-5, reconstruct from a quorum, open the seal.mjs-sealed
        artifact — the FORMAT never changed, only who holds the key."""
        artifact = json.loads((FIXTURES / "parity.sealed.json").read_text())
        shares = split(_fixture_scalar(), 5, 3)
        with SecretBuffer(combine([shares[1], shares[3], shares[4]])) as key:
            got = ts.open_sealed(artifact, key.bytes())
        assert b"synthetic" in got or b"SYN-" in got


class TestReverseParity:
    """Python → Node: the OTHER direction the static fixtures never covered.
    Python seals/signs, then the champollion CLI (seal.mjs) opens/verifies —
    closing the 'either CLI verifies the other's output' claim. Skips cleanly
    where node / the cli tree is absent (the Phase-A pattern)."""

    def _cli(self):
        import shutil
        if shutil.which("node") is None:
            pytest.skip("node not available for the reverse parity check")
        try:
            from mt_eval_harness.contest_prep import find_champollion_cli
            return find_champollion_cli()
        except Exception:
            pytest.skip("champollion CLI not resolvable in this tree")

    def test_python_seal_opens_in_node(self, tmp_path):
        import subprocess
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import x25519
        cli = self._cli()

        priv = x25519.X25519PrivateKey.generate()
        scalar = priv.private_bytes(serialization.Encoding.Raw,
                                    serialization.PrivateFormat.Raw,
                                    serialization.NoEncryption())
        pub_der = ts.derive_x25519_public_spki_der(scalar)
        priv_der = priv.private_bytes(serialization.Encoding.DER,
                                      serialization.PrivateFormat.PKCS8,
                                      serialization.NoEncryption())
        plaintext = b'[{"source": "reverse synthetic", "target": "SYN-rev"}]'
        aad = ts.build_aad("eval-reverse-v1", "grp-rev")
        sealed = ts.seal_bytes(plaintext, pub_der, aad)
        artifact = ts.build_sealed_artifact(
            sealed, card_id="eval-reverse-v1", custodian_group_id="grp-rev")
        art_f = tmp_path / "artifact.sealed.json"
        art_f.write_text(json.dumps(artifact), encoding="utf-8")
        key_f = tmp_path / "recipient.key.json"
        key_f.write_text(json.dumps({
            "publicKeyDerB64": base64.b64encode(pub_der).decode(),
            "privateKeyDerB64": base64.b64encode(priv_der).decode(),
            "keyId": ts.key_id_for_spki_der(pub_der)}), encoding="utf-8")
        out_f = tmp_path / "opened.json"
        proc = subprocess.run(
            cli + ["seal-corpus", "open", "--artifact", str(art_f),
                   "--privkey", str(key_f), "--out", str(out_f)],
            capture_output=True, text=True, timeout=120)
        assert proc.returncode == 0, proc.stderr or proc.stdout
        assert out_f.read_bytes() == plaintext

    def test_python_signature_verifies_in_node(self, tmp_path):
        import subprocess
        cli = self._cli()

        pair = ts.generate_signing_keypair()
        payload = b'{"scores":{"chrf":12.5},"synthetic":true}'
        payload_f = tmp_path / "payload.json"
        payload_f.write_bytes(payload)
        block = ts.sign_payload(payload,
                                base64.b64decode(pair["privateKeyDerB64"]))
        sig_f = tmp_path / "sig.json"
        sig_f.write_text(json.dumps(block), encoding="utf-8")
        pub_f = tmp_path / "sign.pub.json"
        pub_f.write_text(json.dumps(
            {"publicKeyDerB64": pair["publicKeyDerB64"],
             "keyId": pair["keyId"]}), encoding="utf-8")
        proc = subprocess.run(
            cli + ["seal-corpus", "verify", "--payload", str(payload_f),
                   "--sig", str(sig_f), "--pubkey", str(pub_f)],
            capture_output=True, text=True, timeout=120)
        assert proc.returncode == 0, proc.stderr or proc.stdout


# ---------------------------------------------------------------------------
# Python-side roundtrip + refusal edges.
# ---------------------------------------------------------------------------

class TestPythonSealOpen:
    def _sealed(self, plaintext=b'{"synthetic": true}'):
        scalar = secrets.token_bytes(32)
        pub = ts.derive_x25519_public_spki_der(scalar)
        aad = ts.build_aad("eval-x-v1", "group-x")
        return scalar, ts.seal_bytes(plaintext, pub, aad)

    def test_roundtrip(self):
        scalar, sealed = self._sealed(b"synthetic plaintext 123")
        assert sealed["cipher"] == ts.SEAL_CIPHER
        assert ts.open_sealed(sealed, scalar) == b"synthetic plaintext 123"

    def test_wrong_key_refused(self):
        _, sealed = self._sealed()
        with pytest.raises(ts.ThresholdSealError, match="wrong key|tampered"):
            ts.open_sealed(sealed, secrets.token_bytes(32))

    def test_tampered_ciphertext_refused(self):
        scalar, sealed = self._sealed()
        ct = bytearray(base64.b64decode(sealed["ciphertext"]))
        ct[0] ^= 0xFF
        sealed["ciphertext"] = base64.b64encode(bytes(ct)).decode()
        with pytest.raises(ts.ThresholdSealError,
                           match="integrity|digest"):
            ts.open_sealed(sealed, scalar)

    def test_wrong_aad_refused(self):
        scalar, sealed = self._sealed()
        with pytest.raises(ts.ThresholdSealError):
            ts.open_sealed(sealed, scalar,
                           aad=ts.build_aad("eval-OTHER-v1", "group-x"))

    def test_unknown_cipher_refused(self):
        scalar, sealed = self._sealed()
        sealed["cipher"] = "rot13-hope"
        with pytest.raises(ts.ThresholdSealError, match="cipher"):
            ts.open_sealed(sealed, scalar)

    def test_empty_plaintext_refused(self):
        with pytest.raises(ts.ThresholdSealError, match="empty"):
            self._sealed(b"")

    def test_card_block_has_exact_schema_fields(self):
        _, sealed = self._sealed()
        block = ts.build_sealed_card_block(
            sealed, custodian_group_id="group-x",
            key_scheme="shamir-gf256-3-of-5")
        assert set(block) == {"cipher", "custodianGroupId",
                              "ciphertextDigest", "aad", "thresholdKeyId",
                              "keyScheme", "qualifierId",
                              "qualifierThreshold", "artifactRef"}
        # The schema's required four are populated.
        for req in ("cipher", "custodianGroupId", "ciphertextDigest", "aad"):
            assert block[req]


class TestSealCorpusToArtifact:
    def test_writes_artifact_and_card_block(self, tmp_path):
        corpus = tmp_path / "c.json"
        corpus.write_text('[{"source": "syn", "target": "syn-t"}]')
        scalar = secrets.token_bytes(32)
        pub_b64 = base64.b64encode(
            ts.derive_x25519_public_spki_der(scalar)).decode()
        pub_file = tmp_path / "pub.json"
        pub_file.write_text(json.dumps({
            "publicKeyDerB64": pub_b64, "keyScheme": "shamir-gf256-3-of-5"}))
        out = ts.seal_corpus_to_artifact(
            corpus, pub_file, card_id="eval-a-v1",
            custodian_group_id="grp", out_dir=tmp_path / "sealed")
        artifact = json.loads(Path(out["artifact_path"]).read_text())
        block = json.loads(Path(out["block_path"]).read_text())
        assert artifact["champollionSealed"] == ts.SEAL_VERSION
        assert artifact["cardId"] == "eval-a-v1"
        assert "source" not in artifact.get("ciphertext", "")[:0]  # shape only
        assert block["keyScheme"] == "shamir-gf256-3-of-5"
        # And the artifact opens back to the corpus bytes.
        assert ts.open_sealed(artifact, scalar) == corpus.read_bytes()
        # No plaintext token in either written file.
        for p in (out["artifact_path"], out["block_path"]):
            assert b"syn-t" not in Path(p).read_bytes()


class TestSigning:
    def test_sign_verify_roundtrip_and_tamper(self):
        pair = ts.generate_signing_keypair()
        priv = base64.b64decode(pair["privateKeyDerB64"])
        pub = base64.b64decode(pair["publicKeyDerB64"])
        block = ts.sign_payload(b"scores-bytes", priv)
        assert block["scheme"] == ts.SIGN_SCHEME
        assert block["keyId"] == pair["keyId"]
        assert ts.verify_payload(b"scores-bytes", block["signatureB64"], pub)
        assert not ts.verify_payload(b"scores-bytes!",
                                     block["signatureB64"], pub)

    def test_load_key_material_prefers_the_wanted_half(self, tmp_path):
        pair = ts.generate_signing_keypair()
        f = tmp_path / "k.key.json"
        f.write_text(json.dumps(pair))
        assert ts.load_key_material(f, want="public") == base64.b64decode(
            pair["publicKeyDerB64"])
        assert ts.load_key_material(f, want="private") == base64.b64decode(
            pair["privateKeyDerB64"])
        pub_only = tmp_path / "k.pub.json"
        pub_only.write_text(json.dumps(
            {"publicKeyDerB64": pair["publicKeyDerB64"]}))
        with pytest.raises(ts.ThresholdSealError, match="privateKeyDerB64"):
            ts.load_key_material(pub_only, want="private")


class TestSecretBuffer:
    def test_zero_on_close_and_source_zeroed(self):
        src = bytearray(b"\xaa" * 32)
        buf = SecretBuffer(src)
        assert src == bytearray(32)          # caller's copy scrubbed
        assert buf.bytes() == b"\xaa" * 32
        buf.close()
        assert buf.closed
        with pytest.raises(RuntimeError):
            buf.bytes()
        buf.close()                          # idempotent

    def test_context_manager_and_repr_never_leak(self):
        with SecretBuffer(b"\x01" * 32) as buf:
            assert len(buf) == 32
            assert "\\x01" not in repr(buf) and "01" * 8 not in repr(buf)
        assert buf.closed

    def test_empty_refused(self):
        with pytest.raises(ValueError):
            SecretBuffer(b"")
