"""Packaging shim — guarantees the dataset registry ships in every dist.

All metadata lives in ``pyproject.toml``; this file exists ONLY to bundle
``datasets/registry.json`` (the tracked SSOT, ~10 MB) into the package as
``mt_eval_harness/data/registry.json`` — the offline fallback that
``config.load_registry`` resolves (step 3) on a standalone ``pip install``.

Why a shim is needed: the in-package copy is GITIGNORED (generated by
``scripts/build_registry.py``), so on a clean checkout the plain
``[tool.setuptools.package-data]`` rule would silently ship nothing and a
fresh install would crash on ``mt-eval list datasets``.

Two hooks make the copy exist in every artifact, fail-loud:

- ``sdist``: copies the SSOT into ``mt_eval_harness/data/`` BEFORE the
  manifest is assembled. This matters because ``python -m build`` builds the
  wheel FROM the sdist (where ``datasets/`` is not shipped) — the registry
  must already be inside the sdist. If this run created the working-tree
  copy, it is removed again afterwards so the source tree stays clean.
- ``build_py``: after the normal build, copies the SSOT (when present —
  i.e. building from a checkout) directly into ``build_lib`` so direct
  wheel builds need no pre-generated copy either; when building from an
  sdist it verifies the bundled copy actually landed, and errors if not.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py as _build_py
from setuptools.command.sdist import sdist as _sdist

HERE = Path(__file__).resolve().parent
REGISTRY_SSOT = HERE / "datasets" / "registry.json"
BUNDLED_REL = Path("mt_eval_harness") / "data" / "registry.json"


def _refresh_source_copy() -> bool:
    """Copy the SSOT registry to mt_eval_harness/data/registry.json.

    Returns True when this call CREATED the file (caller may clean it up);
    False when it already existed (refreshed in place) or when the SSOT is
    absent (building from an sdist, where the bundled copy already travels).
    """
    if not REGISTRY_SSOT.is_file():
        return False
    dest = HERE / BUNDLED_REL
    created = not dest.is_file()
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(REGISTRY_SSOT, dest)
    return created


class sdist(_sdist):
    """Ensure the bundled registry is inside the sdist file list."""

    def run(self):
        created = _refresh_source_copy()
        try:
            super().run()
        finally:
            if created:
                dest = HERE / BUNDLED_REL
                dest.unlink(missing_ok=True)
                try:  # drop the data/ dir only if we created it and it's empty
                    dest.parent.rmdir()
                except OSError:
                    pass


class build_py(_build_py):
    """Ensure the bundled registry lands in build_lib (→ the wheel)."""

    def run(self):
        super().run()
        target = Path(self.build_lib) / BUNDLED_REL
        if REGISTRY_SSOT.is_file():
            # Building from a checkout: copy straight into build_lib so the
            # source tree stays clean and the wheel still carries the SSOT.
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(REGISTRY_SSOT, target)
        elif not target.is_file():
            # Building from an sdist without the bundled copy — a broken
            # artifact. Fail loud rather than ship a wheel that crashes on
            # `mt-eval list datasets`.
            raise RuntimeError(
                "mt_eval_harness/data/registry.json is missing from this "
                "build. Build from the repo (arena/datasets/registry.json "
                "present) or from an sdist produced by `python -m build`, "
                "which bundles it."
            )


setup(cmdclass={"sdist": sdist, "build_py": build_py})
