// @ts-check

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {themes as prismThemes} from 'prism-react-renderer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Licensed-source count for the homepage proof strip and the research page —
// read at BUILD TIME from the license register rollup so the displayed number
// can never drift from shared/licenses.json (regenerated by
// mt-eval-arena/scripts/build-shared-licenses.mjs). Same root-SSOT-first,
// bundled-copy-fallback resolution as plugins/shared-data. FAIL LOUD: a
// missing or malformed register must break the build, never render a stale
// or invented count.
const licensesJsonPath = [
  path.resolve(__dirname, '..', '..', 'shared', 'licenses.json'),
  path.resolve(__dirname, '..', 'shared', 'licenses.json'),
].find((p) => fs.existsSync(p));
if (!licensesJsonPath) {
  throw new Error(
    '[docusaurus.config] shared/licenses.json not found (repo root or cli/shared) — cannot resolve the licensed-source count.',
  );
}
const licensesRegister = JSON.parse(fs.readFileSync(licensesJsonPath, 'utf8'));
const licensedSourceCount = licensesRegister?._generated?.counts?.total;
const licensedSourceDate = String(licensesRegister?._generated?.generatedAt || '').slice(0, 10);
if (!Number.isInteger(licensedSourceCount) || licensedSourceCount <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(licensedSourceDate)) {
  throw new Error(
    `[docusaurus.config] ${licensesJsonPath} has no valid _generated.counts.total / _generated.generatedAt — refusing to build with an unknown licensed-source count.`,
  );
}

// Dataset-registry count for /research and the who-benefits page — read at
// BUILD TIME from the corpora SSOT (arena/datasets/registry.json). Falls back
// to static/registry.json, the verbatim copy ensure-network-artifacts stages
// at prebuild, so cli/website-only deploys still resolve it. FAIL LOUD.
const registryJsonPath = [
  path.resolve(__dirname, '..', '..', 'arena', 'datasets', 'registry.json'),
  path.resolve(__dirname, 'static', 'registry.json'),
].find((p) => fs.existsSync(p));
if (!registryJsonPath) {
  throw new Error(
    '[docusaurus.config] dataset registry not found (arena/datasets/registry.json or static/registry.json) — cannot resolve the dataset count.',
  );
}
const registryDatasetCount = JSON.parse(fs.readFileSync(registryJsonPath, 'utf8'))?.datasets?.length;
if (!Number.isInteger(registryDatasetCount) || registryDatasetCount <= 0) {
  throw new Error(
    `[docusaurus.config] ${registryJsonPath} has no datasets[] — refusing to build with an unknown dataset count.`,
  );
}

// Catalogue size = the language-card SSOT: one card file per catalogued
// language (language-tree.json is layout metadata, not a card). The same
// gate build-trading-card-data.mjs uses, so this count equals the published
// trading-card index by construction.
const cardsDir = path.resolve(__dirname, '..', 'shared', 'language-cards');
if (!fs.existsSync(cardsDir)) {
  throw new Error(
    `[docusaurus.config] language-card SSOT not found at ${cardsDir} — cannot resolve the catalogue count.`,
  );
}
// LANGUAGES, NOT CARD FILES.
//
// The corpus now also holds 8,675 LOCALE cards — `fra-CA` is French as spoken
// in Canada, a projection of French, not a second language. Counting files
// gave 17,360 and this number is rendered by <SSOTCount> on six public pages,
// so the site would have claimed roughly twice the languages it indexes, with
// French counted once per territory it is spoken in.
//
// A locale names its parent in `locale.language`; that is the discriminator,
// never the shape of the code. cli/scripts/check-prose-counts-parity.mjs
// filters the same way — the two agreed on the rule and disagreed on the
// number, and the parity gate could not catch it because this value reaches
// the page through a component rather than as literal prose.
const catalogLanguageCount = fs
  .readdirSync(cardsDir)
  .filter((f) => f.endsWith('.json') && f !== 'language-tree.json')
  .filter((f) => {
    try {
      const c = JSON.parse(fs.readFileSync(path.join(cardsDir, f), 'utf-8'));
      return !c?.locale?.language;
    } catch {
      // An unreadable card is counted rather than silently dropped; the card
      // linter is what reports it, and swallowing it here would shrink a
      // public number for a reason nobody could see.
      return true;
    }
  }).length;
if (catalogLanguageCount <= 0) {
  throw new Error(
    `[docusaurus.config] language-card SSOT at ${cardsDir} is empty — refusing to build with an unknown catalogue count.`,
  );
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'champollion',
  tagline: 'Source-available infrastructure for trustworthy machine translation across every language — free for noncommercial use, built with communities, never scraped, every method welcome.',
  favicon: 'img/favicon.svg',

  // Build-time facts from the license register (read above). Pages consume
  // these via useDocusaurusContext().siteConfig.customFields instead of
  // carrying a hardcoded copy that drifts when the register regenerates.
  customFields: {
    licensedSourceCount,
    licensedSourceDate,
    registryDatasetCount,
    catalogLanguageCount,
  },

  future: {
    v4: true,
  },

  // Production URL — Vercel + custom domain
  url: 'https://champollion.dev',
  baseUrl: '/',
  trailingSlash: false,

  // GitHub coordinates for "Edit this page" links
  organizationName: 'gamedaysuits',
  projectName: 'champollion',

  onBrokenLinks: 'throw',
  // Broken ANCHORS stay non-fatal: the translated-heading #anchor rewrite is a
  // known, separate i18n gap (champollion doesn't rewrite translated heading
  // ids) and must never turn a production build red. 'warn' is the Docusaurus
  // default — pinned explicitly so it can't regress to 'throw'.
  onBrokenAnchors: 'warn',

  // ALL head tags live in this ONE array. A second `headTags:` key later in
  // this object literal silently replaces this one (later duplicate key wins,
  // and no repo lane runs tsc to flag it) — that is exactly how the font
  // preloads were dead in production until 2026-07-19.
  //
  // Font preloads: the two self-hosted variable fonts used above the fold
  // (Fraunces display serif + Inter UI). Absolute /fonts paths resolve to
  // the root (en) build's copy for every locale, like /data (shared-data).
  // Global meta tags: fallback for pages without explicit descriptions.
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        href: '/fonts/fraunces-latin-opsz-normal.woff2',
        as: 'font',
        type: 'font/woff2',
        crossorigin: 'anonymous',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        href: '/fonts/inter-latin-opsz-normal.woff2',
        as: 'font',
        type: 'font/woff2',
        crossorigin: 'anonymous',
      },
    },
    { tagName: 'meta', attributes: { name: 'description', content: 'Source-available infrastructure for trustworthy machine translation across every language — the test sets and the map that show who can translate what and how good each method is. Public benchmarks on open data rank every method; sovereign benchmarks are secret community-owned test sets we never see. Built with communities, never scraped from them; every method welcome, human and machine.' } },
    { tagName: 'meta', attributes: { name: 'keywords', content: 'machine translation, i18n, localization, low-resource languages, MT evaluation, CLI, benchmarks' } },
  ],

  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'fr', 'de', 'nl', 'fil', 'es', 'zh', 'ja', 'ko', 'pt', 'th', 'vi', 'ar'],
    // Explicit per-locale baseUrl. Why: the production build runs one locale
    // per process (scripts/build-all-locales.mjs) to avoid the all-locales
    // single-process OOM. Docusaurus normally only derives the "/<locale>/"
    // sub-path when building ALL locales together; a lone `--locale fr` flips
    // into multi-domain mode (baseUrl "/"), which would emit fr at the root and
    // clobber the en build. Pinning baseUrl here forces the sub-path in every
    // mode, so per-locale child builds compose into the same build/ + build/<l>/
    // tree as the all-in-one build. (The values equal what Docusaurus infers
    // for the all-in-one build, so that build's output is unchanged.)
    localeConfigs: {
      en:  { label: 'English',     baseUrl: '/' },
      fr:  { label: 'Français',    baseUrl: '/fr/' },
      de:  { label: 'Deutsch',     baseUrl: '/de/' },
      nl:  { label: 'Nederlands',  baseUrl: '/nl/' },
      fil: { label: 'Filipino',    baseUrl: '/fil/' },
      es:  { label: 'Español',     baseUrl: '/es/' },
      zh:  { label: '简体中文',     baseUrl: '/zh/' },
      ja:  { label: '日本語',       baseUrl: '/ja/' },
      ko:  { label: '한국어',       baseUrl: '/ko/' },
      pt:  { label: 'Português',   baseUrl: '/pt/' },
      th:  { label: 'ไทย',         baseUrl: '/th/' },
      vi:  { label: 'Tiếng Việt',  baseUrl: '/vi/' },
      ar:  { label: 'العربية', direction: 'rtl', baseUrl: '/ar/' },
    },
  },

  // Enable Mermaid diagrams in Markdown
  markdown: {
    mermaid: true,
    format: 'detect',
  },
  themes: [
    '@docusaurus/theme-mermaid',
    ['@easyops-cn/docusaurus-search-local', {
      hashed: true,
      indexBlog: false,
      // One docs tree now — the Translate docs and the Network section both
      // live under /docs (Network in docs/network/*), so one route base path.
      docsRouteBasePath: '/docs',
    }],
  ],

  plugins: [
    // Serves the ~600 MB language-card dataset from a single /data path at
    // the build root instead of duplicating it into all 13 locale builds.
    './plugins/shared-data',
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: './sidebars.js',
          editUrl: 'https://github.com/gamedaysuits/Champollion/tree/main/cli/website/',
          // Versioning — snapshot current docs as a version
          lastVersion: 'current',
          versions: {
            current: {
              label: '3.3.0',
              path: '',
            },
          },
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl: 'https://github.com/gamedaysuits/Champollion/tree/main/cli/website/',
          blogTitle: 'champollion Blog',
          blogDescription: 'Release notes, technical deep-dives, and translation engineering insights.',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      image: 'img/champollion-social-card.png',

      // Honest framing: the index is under active development and the data is
      // still being verified against sources. Set expectations + invite the beta.
      announcementBar: {
        id: 'wip-beta-2026',
        content:
          '🚧 <strong>Work in progress.</strong> Champollion is in active development — the index is still being verified against its sources. <a href="/get-involved"><strong>Get involved →</strong></a>',
        backgroundColor: '#1a1730',
        textColor: '#f4f3ff',
        isCloseable: true,
      },

      colorMode: {
        defaultMode: 'dark',
        respectPrefersColorScheme: true,
      },

      navbar: {
        title: 'champollion',
        logo: {
          alt: 'champollion — rosetta fragment mark: a stone with three registers of script',
          src: 'img/logo.svg',
          srcDark: 'img/logo-dark.svg',
          width: 28,
          height: 28,
        },
        // PARED-DOWN nav (founder 2026-07-17): five items, ONE dropdown.
        // The old seven-menu bar (Translate/Explore/Leaderboard/Build/
        // Contribute/Who-it's-for/Docs, five dropdowns) was unwieldy; every
        // page it linked stays live and reachable contextually:
        //   /human-services ← linked from /translate
        //   /route, /glossary ← linked from the Atlas + docs sidebar
        //   /arena, /contribute, /my-language, sovereignty docs ← /get-involved
        //   the six audience doors → merged into /docs/network/who-benefits
        items: [
          {to: '/translate', label: 'Translate', position: 'left'},
          {
            type: 'dropdown',
            label: 'Explore',
            position: 'left',
            items: [
              {to: '/languages', label: 'The Language Atlas'},
              {to: '/catalogue', label: 'The Index'},
              {to: '/leaderboard', label: 'Leaderboard'},
              {to: '/shared-tasks', label: 'Shared tasks & contests'},
              {to: '/for-agents', label: 'For AI agents'},
            ],
          },
          {to: '/docs/network/who-benefits', label: 'Why it matters', position: 'left'},
          {to: '/get-involved', label: 'Get involved', position: 'left'},
          {
            type: 'docSidebar',
            sidebarId: 'docsSidebar',
            label: 'Docs',
            position: 'left',
          },
          {
            type: 'localeDropdown',
            position: 'right',
          },
          {
            href: 'https://github.com/gamedaysuits/Champollion',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },

      // Footer — one unified build, so internal links use root-relative `to:`
      // (SPA navigation + build-time broken-link checking). The Network docs
      // live at /docs/network/* in this same docs tree. Only genuinely external
      // links (GitHub, npm) use `href`.
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Champollion',
            items: [
              {
                label: 'Getting Started',
                to: '/docs/getting-started/quick-start',
              },
              {
                label: 'Leaderboard',
                to: '/leaderboard',
              },
              {
                label: 'Languages',
                to: '/languages',
              },
              {
                label: 'Contribute Compute',
                to: '/contribute',
              },
              {
                label: 'For AI Agents',
                to: '/for-agents',
              },
            ],
          },
          {
            title: 'Network',
            items: [
              {
                label: 'How the Network Works',
                to: '/docs/network',
              },
              {
                label: 'Shared Tasks & Contests',
                to: '/shared-tasks',
              },
              {
                label: 'Submit a Method',
                to: '/docs/network/getting-started/submit-a-method',
              },
              {
                label: 'Human Translation',
                to: '/human-services',
              },
              {
                label: 'Data Sovereignty',
                to: '/docs/network/sovereignty/data-sovereignty',
              },
            ],
          },
          {
            title: 'More',
            items: [
              {
                label: 'Blog',
                to: '/blog',
              },
              {
                label: 'Research',
                to: '/research',
              },
              {
                label: 'Press & Media',
                to: '/docs/network/who-benefits#press',
              },
              {
                label: 'Funders & Sponsors',
                to: '/docs/network/who-benefits#funders',
              },
              {
                label: 'On the Name',
                to: '/docs/the-name',
              },
              {
                label: 'GitHub',
                href: 'https://github.com/gamedaysuits/Champollion',
              },
              {
                label: 'npm',
                href: 'https://www.npmjs.com/package/champollion',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Curtis Forbes. Built with Docusaurus.`,
      },

      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['bash', 'json', 'toml', 'yaml', 'python'],
        magicComments: [
          {
            className: 'theme-code-block-highlighted-line',
            line: 'highlight-next-line',
            block: {start: 'highlight-start', end: 'highlight-end'},
          },
        ],
      },

      // Mermaid theme configuration
      mermaid: {
        theme: {light: 'neutral', dark: 'dark'},
      },
    }),
};

export default config;
