#!/usr/bin/env python3
"""Generate the forge command reference from the argparse parser itself.

Single source of truth: the reference doc is DERIVED from
``nmt_forge.cli.build_parser()``, so it cannot drift from the actual flags. Run
after any CLI change:

    PYTHONPATH=. python3 scripts/gen_command_reference.py \
        --out ../cli/website/docs/network/getting-started/forge-command-reference.md

The output is a Docusaurus markdown page (front-matter + one section per
subcommand, with positionals and options). It is intentionally content-free of
any corpus data — it reflects only the parser structure.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

FORGE_ROOT = Path(__file__).resolve().parents[1]
if str(FORGE_ROOT) not in sys.path:
    sys.path.insert(0, str(FORGE_ROOT))

from nmt_forge.cli import build_parser  # noqa: E402

FRONT_MATTER = """---
sidebar_position: 5
title: forge Command Reference
description: Every nmt-forge subcommand, its arguments, and what it guards — generated from the CLI parser so it never drifts.
---

<!-- GENERATED by forge/scripts/gen_command_reference.py — do not edit by hand.
     Re-run the generator after any CLI change. -->

# forge Command Reference

Every `nmt-forge` subcommand, generated directly from the CLI parser so this
page cannot drift from the tool. For the *why* behind each guard, see
[Train a Model Honestly](/docs/network/getting-started/training-honestly); for
driving forge from an agent, see
[Train Your First Model (with your agent)](/docs/network/getting-started/train-your-first-model).

**The global flag:** `--workspace <dir>` (default `./.forge`) precedes every
subcommand and names the project you are operating on.

Agents: call `nmt-forge status --json` first — it tells you which of these to
run next.

"""


def _subactions(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _render_parser(name: str, parser: argparse.ArgumentParser, level: int,
                   lines: list[str]) -> None:
    heading = "#" * level
    lines.append(f"{heading} `{name}`")
    lines.append("")
    if parser.description and level == 2:
        lines.append(parser.description.strip())
        lines.append("")

    positionals, optionals = [], []
    sub = None
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            sub = action
            continue
        if isinstance(action, argparse._HelpAction):
            continue
        if action.option_strings:
            optionals.append(action)
        else:
            positionals.append(action)

    if positionals:
        lines.append("**Arguments:**")
        lines.append("")
        for a in positionals:
            if isinstance(a, argparse._SubParsersAction):
                continue
            lines.append(f"- `{a.dest}` — {(a.help or '').strip()}")
        lines.append("")
    if optionals:
        lines.append("**Options:**")
        lines.append("")
        for a in optionals:
            flag = ", ".join(f"`{s}`" for s in a.option_strings)
            meta = ""
            if a.choices:
                meta = f" (one of: {', '.join(map(str, a.choices))})"
            req = " *(required)*" if a.required else ""
            lines.append(f"- {flag}{req}{meta} — {(a.help or '').strip()}")
        lines.append("")

    if sub is not None:
        for choice, subparser in sub.choices.items():
            _render_parser(f"{name} {choice}", subparser, level + 1, lines)


def generate() -> str:
    ap = build_parser()
    lines: list[str] = [FRONT_MATTER]
    sub = _subactions(ap)
    # help text per subcommand comes from the subparser action's choices
    help_by_name = {}
    if sub is not None:
        for act in sub._choices_actions:
            help_by_name[act.dest] = act.help
        for choice, subparser in sub.choices.items():
            _render_parser(choice, subparser, 2, lines)
            # inject the one-line help under the heading if the subparser has
            # no description of its own
            if not subparser.description and help_by_name.get(choice):
                idx = lines.index(f"## `{choice}`") + 2
                lines.insert(idx, help_by_name[choice].strip())
                lines.insert(idx + 1, "")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", default=None,
                   help="write the reference here (default: stdout)")
    args = p.parse_args()
    text = generate()
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out} ({text.count(chr(10))} lines)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
