/**
 * ZipperSeam v6 — 6-beat cinematic scroll narrative.
 *
 * v6 design pass (founder directive): every claim readable by a 70-year-old
 * on a laptop — WCAG AA minimum contrast, ~12px effective floor everywhere
 * (including scaled SVG text), score chips legible at a glance. Scores are
 * chrF++ on sacrebleu's 0–100 scale (matching the rest of the site, not 0–1),
 * chips carry a plain-language <Tip>, and the sovereign beat's score is
 * explicitly an illustration ("certified" dropped — no sealed-set run has
 * published yet).
 *
 * Tells the Champollion two-tier vision arc:
 *   1. THE PROBLEM   — the race to build one model that speaks every language.
 *   2. MEASURE       — instead, score every method (human or machine), pair by pair.
 *   3. THE OPEN MAP  — every measured pair lights up the public map (Tier 1).
 *   4. TRACEABLE     — proof: a real chain, every hop auditable, every corpus licensed.
 *   5. THE SEAL      — the apex: a community's sealed test set certifies a method
 *                      without anyone — not even Champollion — ever seeing the data (Tier 2).
 *   6. THE MISSION   — every language into every language, under terms its people set.
 *
 * Architecture:
 *   Each beat is a full-viewport layer. GSAP ScrollTrigger pins the
 *   section and scrubs a master timeline that cross-fades layers with
 *   explicit opacity gates — every beat sets its layer to 1 on enter
 *   and 0 on exit, so nothing leaks between states.
 */
import React, {useEffect, useRef, useState} from 'react';
import clsx from 'clsx';
import BrandMark from './BrandMark';
import Tip from './Tip';
import {termAnchor} from '../utils/explainerLoader';
import styles from './ZipperSeam.module.css';
// Build-time poster stats (counts read from the cited cards) — so the mission
// "living languages" number is the real, current count, never a hardcoded guess.
import poster from '../data/graph-poster.json';
// The house-style lock-and-pop + the quality-colour SSOT (founder 2026-07-20/21):
// colour carries meaning — green = deployable, orange = measured-not-great,
// red = not reliable; a route is only as good as its weakest hop.
import {addLockPop} from '../utils/lockPop.mjs';
import {QUALITY} from '../utils/qualityColors.mjs';
// The house word-reveal, extracted 2026-07-22 so every scroll story stitches
// type the same way (home-preview shares it). Bound to this seam's gsap/
// SplitText/timeline inside the effect below.
import {stitchIn as sharedStitchIn} from '../utils/stitchIn.mjs';

/* ───────── DATA ───────── */

/**
 * The TRUE omnimodel scene (v7, founder 2026-07-17): poster.monolith carries
 * real sampled layout positions of LIVING languages flagged covered/uncovered
 * by NLLB-200 (bit 16; generated by generateGraphJson.js v10). When present,
 * Beat 1 renders the real field — NLLB's covered set in its service teal, the
 * uncovered living mass flushing ember — instead of the legacy decorative
 * SPOKES. Stale poster without `monolith` → the legacy scene renders (the
 * timeline keys off element presence, so both paths share one effect).
 */
const MONO = poster.monolith || null;

/** Group the uncovered points into N equal-count radial cohorts so the ember
 *  "flush" is N group tweens sweeping outward — never per-dot scrub tweens. */
function monolithCohorts(mono, nCohorts = 8) {
  if (!mono || !Array.isArray(mono.pts) || !mono.pts.length) return null;
  const cx = mono.box[0] / 2;
  const cy = mono.box[1] / 2;
  const covered = [];
  const uncovered = [];
  for (const p of mono.pts) (p[2] ? covered : uncovered).push(p);
  const withD = uncovered
    .map((p) => ({p, d: Math.hypot(p[0] - cx, p[1] - cy)}))
    .sort((a, b) => a.d - b.d);
  const cohorts = Array.from({length: nCohorts}, () => []);
  withD.forEach((e, i) => {
    cohorts[Math.min(nCohorts - 1, Math.floor((i * nCohorts) / withD.length))].push(e.p);
  });
  return {covered, cohorts};
}
const MONO_FIELD = monolithCohorts(MONO);

// ── Storyboard field data (Beat 1 rebuild) ── reuses the monolith positions:
// covered dots (green-able) + uncovered dots x-sorted into BANDS for the
// left→right red wave + a sparse mesh over the covered set + the provider hubs.
const _FPTS = MONO && Array.isArray(MONO.pts) ? MONO.pts : [];
const FIELD_COVERED = _FPTS.filter((p) => p[2] === 1);
const FIELD_UNCOVERED = _FPTS.filter((p) => p[2] === 0).sort((a, b) => a[0] - b[0]);
const FIELD_BAND_N = 14;
const FIELD_BANDS = Array.from({length: FIELD_BAND_N}, () => []);
FIELD_UNCOVERED.forEach((p, i) => {
  const b = Math.min(FIELD_BAND_N - 1, Math.floor((i / Math.max(FIELD_UNCOVERED.length, 1)) * FIELD_BAND_N));
  FIELD_BANDS[b].push(p);
});
function computeFieldMesh(cov) {
  const edges = [];
  const seen = new Set();
  const step = Math.max(1, Math.floor(cov.length / 110));
  for (let a = 0; a < cov.length && edges.length < 150; a += step) {
    let best = -1;
    let bd = Infinity;
    for (let b = 0; b < cov.length; b += 1) {
      if (b === a) continue;
      const dx = cov[a][0] - cov[b][0];
      const dy = cov[a][1] - cov[b][1];
      const d = dx * dx + dy * dy;
      if (d < bd) {
        bd = d;
        best = b;
      }
    }
    if (best >= 0) {
      const k = a < best ? `${a}-${best}` : `${best}-${a}`;
      if (!seen.has(k)) {
        seen.add(k);
        edges.push([a, best]);
      }
    }
  }
  return edges;
}
const FIELD_MESH = computeFieldMesh(FIELD_COVERED);
const FIELD_HUBS = (MONO && Array.isArray(MONO.methods) ? MONO.methods.slice() : [])
  .sort((a, b) => (b.count || 0) - (a.count || 0))
  .slice(0, 9);

/** Plain-language explainer for the Beat-1 coverage claim — v12 generalizes
 *  the critique from NLLB-only to ALL centralized MT (founder: "the problem
 *  is the same with Google Translate, with most MT"): the field shows every
 *  major service + model COMBINED. Figures recorded in CLAIMS.md. */
const MONO_TIP =
  MONO && Array.isArray(MONO.methods)
    ? {
        term: 'Centralized MT, combined',
        body:
          MONO.methods
            .map((m) => `${m.label} ${m.count.toLocaleString('en-US')}`)
            .join(' · ') +
          ' — each provider’s published coverage list (ISO 639-3), deduplicated ' +
          'and intersected with living languages. The dots are real catalog ' +
          `positions: all ${(MONO.coveredLiving || 0).toLocaleString('en-US')} living ` +
          'languages at least one of them covers, and a ' +
          `${(MONO.uncoveredSampled || 0).toLocaleString('en-US')}-language sample of the ` +
          `${(MONO.uncoveredTotal || 0).toLocaleString('en-US')} covered by none.`,
        href: '/docs/network/who-benefits',
      }
    : null;

/** Monolith spokes — the LEGACY decorative scene (stale-poster fallback only;
 *  the real data path above replaces it). */
const SPOKES = [
  {lang: 'English',   x: 540, y: 200, dim: false},
  {lang: '中文',       x: 520, y: 110, dim: false},
  {lang: 'español',   x: 440, y: 100, dim: false},
  {lang: 'français',  x: 360, y: 120, dim: false},
  {lang: 'العربية',   x: 520, y: 310, dim: false},
  {lang: 'हिन्दी',     x: 430, y: 330, dim: false},
  {lang: 'português', x: 340, y: 310, dim: false},
  {lang: '日本語',     x: 180, y: 130, dim: true},
  {lang: 'isiZulu',   x: 140, y: 230, dim: true},
  {lang: 'Runasimi',  x: 120, y: 300, dim: true},
  {lang: 'Føroysk',   x: 200, y: 340, dim: true},
  {lang: 'Davvisám.', x: 460, y: 350, dim: true},
];

/**
 * Zipper teeth — language pairs that stitch together.
 * Each row has a left (source) and right (target) language.
 *
 * Three rows carry `chain: true`: the SAME pairs as Beat 3/4's showcase
 * pathway (Føroysk→Dansk→Español→Runasimi), deliberately SCATTERED among
 * the others. At the end of the zip they highlight amber so the visitor
 * connects the dots — separate measured pairs chain into a network
 * pathway (founder direction 2026-07-17).
 */
// `q` = the pair's measured quality tier (good | ok | bad) — the zipper is a
// quality readout, not decoration. The three chain pairs are the showcase
// route: Føroysk→Dansk (good) → Español (ok) → Runasimi (BAD) — so the route
// is only as good as that weakest, red hop.
const TEETH = [
  {l: 'العربية',      r: 'isiZulu',  q: 'ok'},
  {l: 'Føroysk',      r: 'Dansk', chain: true, q: 'good'},
  {l: 'English',      r: 'Cymraeg',  q: 'good'},
  {l: '日本語',        r: '한국어',    q: 'good'},
  {l: 'Dansk',        r: 'Español', chain: true, q: 'ok'},
  {l: 'Anishinaabe.', r: 'français', q: 'bad'},
  {l: 'Tok Pisin',    r: 'Bislama',  q: 'ok'},
  {l: 'Español',      r: 'Runasimi', chain: true, q: 'bad'},
  {l: 'Davvisámeg.',  r: 'suomi',    q: 'ok'},
  {l: 'chiShona',     r: 'Chichewa', q: 'good'},
];

/**
 * Network nodes — positioned on a 700×500 viewBox.
 * Groups: european, asian, african, americas, chain (showcase).
 */
const NODES = [
  // European cluster (left-center)
  {id: 'eng', label: 'English',   x: 250, y: 180, hub: true},
  {id: 'fra', label: 'français',  x: 160, y: 130},
  {id: 'deu', label: 'Deutsch',   x: 190, y: 220},
  {id: 'nld', label: 'Nederlands',x: 230, y: 260},
  {id: 'por', label: 'português', x: 140, y: 250},
  {id: 'ita', label: 'italiano',  x: 100, y: 190},
  {id: 'rus', label: 'русский',   x: 310, y: 250},
  // Asian cluster (right)
  {id: 'cmn', label: '中文',       x: 520, y: 150, hub: true},
  {id: 'jpn', label: '日本語',     x: 580, y: 190},
  {id: 'kor', label: '한국어',     x: 560, y: 240},
  {id: 'vie', label: 'Tiếng Việt', x: 490, y: 230},
  {id: 'tha', label: 'ภาษาไทย',   x: 540, y: 290},
  // African
  {id: 'arb', label: 'العربية',   x: 380, y: 130},
  {id: 'sna', label: 'chiShona',  x: 420, y: 310},
  {id: 'amh', label: 'አማርኛ',     x: 360, y: 290},
  // Chain nodes (highlighted path)
  {id: 'fao', label: 'Føroysk',   x: 120, y: 80,  chain: true},
  {id: 'dan', label: 'Dansk',     x: 210, y: 100, chain: true},
  {id: 'spa', label: 'español',   x: 300, y: 160, chain: true},
  {id: 'que', label: 'Runasimi',  x: 380, y: 380, chain: true},
  // LRL nodes
  {id: 'sme', label: 'Davvisám.', x: 160, y: 50},
  {id: 'cym', label: 'Cymraeg',   x: 80,  y: 140},
  {id: 'eus', label: 'Euskara',   x: 200, y: 300},
  {id: 'tgl', label: 'Tagalog',   x: 620, y: 330},
];

/** Edges — pairs of node IDs. */
const EDGES = [
  // European core
  ['eng', 'fra'], ['eng', 'deu'], ['eng', 'spa'], ['eng', 'por'],
  ['eng', 'ita'], ['eng', 'nld'], ['eng', 'rus'], ['eng', 'arb'],
  ['fra', 'deu'], ['fra', 'ita'], ['fra', 'por'], ['fra', 'spa'],
  ['deu', 'nld'], ['deu', 'ita'], ['por', 'ita'], ['por', 'spa'],
  ['nld', 'rus'], ['ita', 'rus'],
  // Asian core
  ['eng', 'cmn'], ['eng', 'jpn'], ['eng', 'kor'], ['eng', 'vie'],
  ['cmn', 'jpn'], ['cmn', 'kor'], ['cmn', 'vie'],
  ['jpn', 'kor'], ['jpn', 'vie'], ['vie', 'tha'],
  // African
  ['eng', 'amh'], ['eng', 'sna'], ['arb', 'amh'], ['sna', 'amh'],
  ['fra', 'arb'],
  // LRL
  ['eng', 'cym'], ['eng', 'sme'], ['eng', 'tgl'],
  ['fra', 'eus'], ['spa', 'eus'],
  // Chain path (highlighted)
  ['fao', 'dan'], ['dan', 'spa'], ['spa', 'que'],
  // Chain adjacent
  ['dan', 'deu'], ['dan', 'nld'], ['sme', 'dan'],
  ['spa', 'tgl'],
];

// Edge quality tiers — colour = measured quality. The chain (route) edges are
// fixed (good → ok → BAD, so the route's weakest hop is red); the rest get a
// believable spread, deterministic so SSR and client agree. `tierHex` maps a
// tier to its brand hex; unknown → slate (unmeasured).
const EDGE_Q = {'fao-dan': 'good', 'dan-spa': 'ok', 'spa-que': 'bad'};
const EDGE_TIER_CYCLE = ['good', 'ok', 'good', 'ok', 'bad', 'good', 'ok', 'good', 'bad', 'ok', 'good'];
function edgeTier(from, to, i) {
  return EDGE_Q[`${from}-${to}`] || EDGE_Q[`${to}-${from}`] || EDGE_TIER_CYCLE[i % EDGE_TIER_CYCLE.length];
}
function tierHex(tier) {
  return tier && QUALITY[tier] ? QUALITY[tier].hex : '#8b95a7';
}

/** Chain showcase: the sentence and its translation at each hop.
 *  Corpus metadata pulled from cli/shared/corpora-cards/*.json. */
const CHAIN_PHRASE = {
  sentence: 'The river carries our ancestors\' stories to the sea.',
  hops: [
    {
      code: 'fao',
      lang: 'Føroysk',
      langEn: 'Faroese',
      text: 'Áin ber søgur av foreldrunum okkara til sjógvs.',
    },
    {
      code: 'dan',
      lang: 'Dansk',
      langEn: 'Danish',
      text: 'Floden bærer vores forfædres historier til havet.',
    },
    {
      code: 'spa',
      lang: 'Español',
      langEn: 'Spanish',
      text: 'El río lleva las historias de nuestros antepasados al mar.',
    },
    {
      code: 'que',
      lang: 'Runasimi',
      langEn: 'Quechua',
      textRough: 'Mayuqa abuelanchikkunapa cuentonkunata mar-man apan.',
      textFixed: 'Mayuqa ñawpa machulanchikkunap willakuyninkunata quchaman apan.',
    },
  ],
  /** Corpus that bridges each hop (index = arrow between hop[i] and hop[i+1]). */
  bridges: [
    {
      corpus: 'Tatoeba dan→fao',
      license: 'CC-BY-2.0',
      pairs: 168,
      quality: 'Human-translated',
      contaminationRisk: 'Medium',
      source: 'tatoeba.org',
    },
    {
      corpus: 'Tatoeba spa→dan',
      license: 'CC-BY-2.0',
      pairs: 111,
      quality: 'Human-translated',
      contaminationRisk: 'Low',
      source: 'tatoeba.org',
    },
    {
      corpus: 'Tatoeba spa→que',
      license: 'CC-BY-2.0',
      pairs: 95,
      quality: 'Human-translated',
      contaminationRisk: 'Low',
      source: 'tatoeba.org',
    },
  ],
};

/** Plain-language chrF++ explainer — same framing as /arena's CHRF_TIP, with
 *  the 0–100 scale stated up front (the seam is the first place a visitor
 *  meets a score chip). Hover/focus on any score chip reveals it. */
const CHRF_TIP = {
  term: 'chrF++',
  body:
    'An automatic score from 0 to 100 — higher is better — measuring how ' +
    'closely a translation’s characters and words overlap a reference ' +
    'translation. It checks surface similarity, not whether every word is real.',
  href: `/glossary#${termAnchor('chrF')}`,
};

// Public read-only anon key (same as GraphHero / leaderboard) — RLS-gated.
const SUPABASE_URL = 'https://sjdomynysdljkbemupqa.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_bV6CFNFnzxhQI0wlBx2J0A_5Vm5gFBp';

/**
 * Live progress stats — REAL counts from the public board, stated with
 * ambition, not fabrication and not false humility. The grid shows how far
 * we've actually got (distinct benchmarked pairs × distinct methods, live from
 * run_cards). Zero is honest on a fresh board; the numbers only climb as the
 * queue runs. The static items anchor the scale + the open ethos.
 *
 * FRAMING (founder ruling 2026-08-21): we are a ROUTING NETWORK, not a
 * coverage claim — this block used to say "we are building toward EVERY
 * language, by EVERY method", which is a promise nobody in the industry meets
 * (the deployable commercial ceiling is 207 ISO 639-3 codes; see
 * docs/competitive/00_ENGINE_CEILING_2026-08-21.md). Note what the cards
 * actually do, and keep it that way: `pairs mapped` and `methods compared` are
 * OUR numbers — what we have measured. `living languages` is the WORLD's
 * number, not a coverage claim about us. Never relabel it as one.
 */
function buildPlatformStats({pairs, methods}) {
  const fmt = (n) => n.toLocaleString('en-US');
  // Read from the same validated SSOT the seam captions use. The old fallback
  // hand-typed '7,000+', which is exactly the silently-wrong display value the
  // founder standard forbids — if the stat is missing we drop the card rather
  // than fabricate a number.
  const living =
    poster.stats && Number.isFinite(poster.stats.livingTotal)
      ? poster.stats.livingTotal
      : null;
  return [
    {number: fmt(pairs), label: pairs === 1 ? 'pair mapped' : 'pairs mapped'},
    {number: fmt(methods), label: methods === 1 ? 'method compared' : 'methods compared'},
    ...(living === null
      ? []
      : [{number: fmt(living), label: 'living languages'}]),
    {number: '100%', label: 'source-available'},
  ];
}

/* ───────── COMPONENT ───────── */

export default function ZipperSeam() {
  const [reduced, setReduced] = useState(false);
  // Live progress: distinct benchmarked pairs × distinct methods, from the
  // public board. Starts at 0 (honest on a fresh board) and only climbs.
  const [stats, setStats] = useState({pairs: 0, methods: 0});

  // Refs for the pin container and each beat layer.
  const seamRef = useRef(null);
  const beat0Ref = useRef(null);
  const beat1Ref = useRef(null);
  const beat2Ref = useRef(null);
  const beat3Ref = useRef(null);
  const beat4Ref = useRef(null);
  const beat5Ref = useRef(null);
  const beat6Ref = useRef(null);
  const networkRef = useRef(null);
  const sliderRef = useRef(null);

  // Detect reduced motion.
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return undefined;
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const update = () => setReduced(mq.matches);
    update();
    mq.addEventListener('change', update);
    return () => mq.removeEventListener('change', update);
  }, []);

  // Live progress counts from the public board (read-only). Distinct
  // language pairs and distinct methods (method_class, falling back to
  // model_slug). Same source as GraphHero's "pairs measured". Honest 0 on a
  // fresh board; offline → stays 0, never fabricated.
  useEffect(() => {
    let cancelled = false;
    fetch(
      `${SUPABASE_URL}/rest/v1/run_cards?select=language_pair,method_class,model_slug&trust=neq.disqualified`,
      {headers: {apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}`}},
    )
      .then((r) => (r.ok ? r.json() : []))
      .then((rows) => {
        if (cancelled || !Array.isArray(rows)) return;
        const pairs = new Set();
        const methods = new Set();
        for (const row of rows) {
          if (/^[a-z]{2,3}>[a-z]{2,3}$/.test(row.language_pair || '')) {
            pairs.add(row.language_pair);
          }
          const method = row.method_class || row.model_slug;
          if (method) methods.add(method);
        }
        setStats({pairs: pairs.size, methods: methods.size});
      })
      .catch(() => {/* board offline — counts stay 0, never fabricated */});
    return () => { cancelled = true; };
  }, []);

  // ── GSAP ScrollTrigger — master timeline ──
  useEffect(() => {
    if (reduced || typeof window === 'undefined') return undefined;

    let ctx = null;
    let cancelled = false;
    const splits = []; // SplitText instances — reverted on teardown (React 19)

    Promise.all([
      import('gsap'),
      import('gsap/ScrollTrigger'),
      // SplitText is free since GSAP 3.13 — the zipper-stitch headlines.
      // Fail-soft: absent/broken plugin → headlines animate whole (v6 look).
      import('gsap/SplitText').catch(() => null),
      // Split AFTER webfonts settle, or the word geometry re-wraps under us.
      typeof document !== 'undefined' && document.fonts && document.fonts.ready
        ? document.fonts.ready.catch(() => null)
        : Promise.resolve(null),
    ]).then(([gsapMod, stMod, splitMod]) => {
      if (cancelled) return;

      const gsap = gsapMod.gsap || gsapMod.default;
      const ScrollTrigger = stMod.ScrollTrigger || stMod.default;
      const SplitText = splitMod ? splitMod.SplitText || splitMod.default : null;
      gsap.registerPlugin(ScrollTrigger);
      if (SplitText) gsap.registerPlugin(SplitText);

      const seam = seamRef.current;
      if (!seam) return;

      ctx = gsap.context(() => {
        // Gather beat layers.
        const b0 = beat0Ref.current;
        const b1 = beat1Ref.current;
        const b2 = beat2Ref.current;
        const b3 = beat3Ref.current;
        const b4 = beat4Ref.current;
        const b5 = beat5Ref.current;
        const b6 = beat6Ref.current;
        const net = networkRef.current;
        const slider = sliderRef.current;
        const beats = [b0, b1, b2, b3, b4, b5, b6].filter(Boolean);

        // Start ALL beat layers at autoAlpha 0 (opacity + visibility:hidden).
        // visibility matters now that beats hold interactive score-chip Tips:
        // an opacity-0 layer would still trap hover/focus over the beat that
        // IS on screen; a hidden one can't.
        gsap.set(beats, {autoAlpha: 0});
        if (net) gsap.set(net, {opacity: 0});

        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: seam,
            start: 'top top',
            end: '+=780%', // was 720% — slide 0 (the project statement) added
            pin: true,
            scrub: 0.5,
            anticipatePin: 1,
          },
        });
        // Debug/review hook (same pattern as window.__GRAPH_ENGINE): lets a
        // review harness step the beats deterministically via
        // __SEAM_TL.pause().progress(x) without scrolling.
        window.__SEAM_TL = tl;

        // ── Zipper-stitch headlines (SplitText, free since GSAP 3.13) ──
        // Even words drop from above, odd words rise from below, stitching
        // shut on the scrub — the section's zipper metaphor, in type.
        // PACING (founder 2026-07-17b: "sentences should click and pause"):
        // the whole line lands inside a FIXED window (`amount` spreads the
        // stagger over the total, however many words there are — never a
        // per-word constant that overruns the beat), each word snaps home
        // with a back.out overshoot, the finished sentence gets a micro
        // scale "click", and callers leave dead scrub after the click so
        // the line HOLDS, readable, before anything else moves. Transform/
        // opacity only (motion contract §5). Returns false when the plugin
        // is unavailable or the line is too short — callers then fall back
        // to the v6 whole-element tween, so the seam never loses a headline.
        // Shared house util (utils/stitchIn.mjs) — this wrapper binds the
        // seam's gsap/SplitText/timeline/styles so the beats below read as
        // before. Extraction 2026-07-22 (home-preview reuses the same util).
        const stitchIn = (el, at, opts = {}) =>
          sharedStitchIn(gsap, SplitText, tl, el, at, {
            wordsClass: styles.splitWord,
            charsClass: styles.splitChar,
            splits,
            ...opts,
          });

        // ════════════════════════════════════════════════
        // SLIDE 0: THE PROJECT (0.00 — 0.05)
        // The strategy statement, alone — moved out of the hero subline
        // (founder 2026-07-17): "open infrastructure to support communities
        // building machine translation". Stitches in, unzips out.
        // ════════════════════════════════════════════════
        if (b0) {
          tl.to(b0, {autoAlpha: 1, duration: 0.012}, 0);
          const openerTitle = b0.querySelector(`.${styles.openerTitle}`);
          const openerSub = b0.querySelector(`.${styles.openerSub}`);
          // Land by 0.028, click, then HOLD assembled until the 0.042 unzip.
          if (openerTitle && !stitchIn(openerTitle, 0.003, {dur: 0.014, amount: 0.011, exitAt: 0.042})) {
            tl.fromTo(openerTitle, {opacity: 0, y: 16}, {opacity: 1, y: 0, duration: 0.02}, 0.004);
          }
          if (openerSub) {
            tl.fromTo(openerSub, {opacity: 0, y: 12}, {opacity: 1, y: 0, duration: 0.016}, 0.03);
            tl.to(openerSub, {opacity: 0, duration: 0.012}, 0.044);
          }
          tl.to(b0, {autoAlpha: 0, duration: 0.012}, 0.048);
        }

        // ════════════════════════════════════════════════
        // BEAT 1: THE PROBLEM — centralized MT, combined (0.05 — 0.15)
        // Every major service + model's covered set pops teal, then the
        // living mass none of them cover flushes ember outward in radial
        // cohorts. Legacy SPOKES path (stale poster) shares this block —
        // tweens key off element presence, so whichever scene rendered
        // simply plays.
        // ════════════════════════════════════════════════
        if (b1) {
          tl.to(b1, {autoAlpha: 1, duration: 0.015}, 0.05);

          const field = b1.querySelector(`.${styles.monolithSvg}`);
          const circle = b1.querySelector(`.${styles.monolith}`);
          const labels = b1.querySelectorAll(`.${styles.monolithLabel}`);
          const subLabel = b1.querySelector(`.${styles.monolithSubLabel}`);
          const spokes = b1.querySelectorAll(`.${styles.spoke}`);
          const spokeLabels = b1.querySelectorAll(`.${styles.spokeLabel}`);
          const coveredG = b1.querySelector(`.${styles.fieldCovered}`);
          const sparkles = b1.querySelectorAll(`.${styles.fieldSparkle}`);
          const cohortEls = b1.querySelectorAll(`.${styles.fieldCohort}`);
          const narr1 = b1.querySelector(`.${styles.narrative}`);
          const kicker1 = b1.querySelector(`.${styles.kicker}`);
          const title1 = b1.querySelector(`.${styles.narrTitle}`);
          const sub1 = b1.querySelector(`.${styles.narrSub}`);
          const stat1 = b1.querySelector(`.${styles.fieldStat}`);
          const legend1 = b1.querySelector(`.${styles.fieldLegend}`);

          if (field) {
            tl.fromTo(field,
              {opacity: 0, scale: 0.94, transformOrigin: '50% 50%'},
              {opacity: 1, scale: 1, duration: 0.025, ease: 'power2.out'},
              0.053
            );
          }
          if (circle) {
            tl.fromTo(circle,
              {scale: 0, opacity: 0, transformOrigin: '300px 200px'},
              {scale: 1, opacity: 1, duration: 0.03, ease: 'power2.out'},
              0.055
            );
          }
          if (labels.length) {
            tl.fromTo(labels, {opacity: 0}, {opacity: 1, stagger: 0.004, duration: 0.022}, 0.068);
          }
          if (subLabel) {
            tl.fromTo(subLabel, {opacity: 0}, {opacity: 1, duration: 0.02}, 0.074);
          }
          // TRUE field: everything centralized MT covers pops teal…
          if (coveredG) {
            tl.fromTo(coveredG,
              {opacity: 0, scale: 0.7, transformOrigin: '50% 50%'},
              {opacity: 1, scale: 1, duration: 0.025, ease: 'back.out(1.4)'},
              0.07
            );
          }
          if (sparkles.length) {
            tl.fromTo(sparkles, {opacity: 0.25}, {opacity: 1, stagger: 0.0005, duration: 0.018}, 0.078);
          }
          // …then the living mass NONE of it covers flushes ember, outward.
          // Timed to COMPLETE (last cohort fully in by ~0.114) before the
          // exit tweens begin at 0.115.
          if (cohortEls.length) {
            cohortEls.forEach((g, ci) => {
              tl.fromTo(g,
                {opacity: 0},
                {opacity: 1, duration: 0.015, ease: 'power1.out'},
                0.075 + ci * 0.0034
              );
            });
          }
          // LEGACY spokes (stale poster only).
          if (spokes.length) {
            tl.fromTo(spokes,
              {scaleX: 0, opacity: 0},
              {scaleX: 1, opacity: 0.6, stagger: 0.004, duration: 0.03},
              0.07
            );
          }
          if (spokeLabels.length) {
            tl.fromTo(spokeLabels,
              {opacity: 0},
              {opacity: 1, stagger: 0.003, duration: 0.02},
              0.08
            );
          }
          // Narrative: kicker → stitched headline → staged sub/stat/legend
          // (the requested early-scroll dynamism: distinct staged pop-ins,
          // not one container fade).
          if (narr1) {
            tl.fromTo(narr1, {opacity: 0}, {opacity: 1, duration: 0.01}, 0.055);
          }
          if (kicker1) {
            tl.fromTo(kicker1, {opacity: 0, y: -8}, {opacity: 1, y: 0, duration: 0.016}, 0.057);
          }
          // Headline lands by 0.088 (13 words spread over the FIXED amount),
          // clicks, and holds; sub/stat/legend settle underneath during the
          // hold; unzip waits until 0.122.
          if (title1 && !stitchIn(title1, 0.06, {dur: 0.016, amount: 0.012, exitAt: 0.122})) {
            tl.fromTo(title1, {opacity: 0, y: 14}, {opacity: 1, y: 0, duration: 0.022}, 0.062);
          }
          if (sub1) {
            tl.fromTo(sub1, {opacity: 0, y: 14}, {opacity: 1, y: 0, duration: 0.02, ease: 'power2.out'}, 0.09);
          }
          if (stat1) {
            tl.fromTo(stat1, {opacity: 0, y: 12}, {opacity: 1, y: 0, duration: 0.02, ease: 'power2.out'}, 0.098);
          }
          if (legend1) {
            tl.fromTo(legend1, {opacity: 0, y: 10}, {opacity: 1, y: 0, duration: 0.016}, 0.105);
          }

          // Exit: ember fades, the covered set contracts, badge collapses.
          if (cohortEls.length) {
            tl.to(cohortEls, {opacity: 0, duration: 0.02}, 0.115);
          }
          if (coveredG) {
            tl.to(coveredG, {scale: 0.6, opacity: 0, transformOrigin: '50% 50%', duration: 0.025}, 0.118);
          }
          if (spokes.length) {
            tl.to(spokes,
              {scaleX: 2.5, opacity: 0, stagger: 0.003, duration: 0.03},
              0.115
            );
          }
          if (spokeLabels.length) {
            tl.to(spokeLabels, {opacity: 0, duration: 0.02}, 0.115);
          }
          if (circle) {
            tl.to(circle, {scale: 0.3, opacity: 0, duration: 0.02}, 0.125);
          }
          if (labels.length) {
            tl.to(labels, {opacity: 0, duration: 0.02}, 0.125);
          }
          if (subLabel) {
            tl.to(subLabel, {opacity: 0, duration: 0.02}, 0.125);
          }
          tl.to(b1, {autoAlpha: 0, duration: 0.02}, 0.14);
        }

        // ════════════════════════════════════════════════
        // BEAT 2: MEASURE EVERY METHOD — the stitch (0.15 — 0.31)
        // ════════════════════════════════════════════════
        if (b2) {
          // Enter as Beat 1's monolith collapses — a cross-dissolve, no
          // fade-through-black between the two scenes.
          tl.to(b2, {autoAlpha: 1, duration: 0.025}, 0.132);

          const leftTeeth = b2.querySelectorAll(`.${styles.toothLeft}`);
          const rightTeeth = b2.querySelectorAll(`.${styles.toothRight}`);
          const connectors = b2.querySelectorAll(`.${styles.connector}`);
          const narr2L = b2.querySelector(`.${styles.stitchLine1}`);
          const narr2R = b2.querySelector(`.${styles.stitchLine2}`);

          if (leftTeeth.length) {
            tl.fromTo(leftTeeth,
              {x: -80, opacity: 0},
              {x: 0, opacity: 1, stagger: 0.008, duration: 0.04, ease: 'power2.out'},
              0.142
            );
          }
          if (rightTeeth.length) {
            tl.fromTo(rightTeeth,
              {x: 80, opacity: 0},
              {x: 0, opacity: 1, stagger: 0.008, duration: 0.04, ease: 'power2.out'},
              0.142
            );
          }
          // The zipper head travels the FULL stage (founder: it stopped too
          // early) and each connector closes top-down just as the head
          // passes its row — the zip follows the head, like a real zipper.
          const ZIP_START = 0.15;
          const ZIP_SPAN = 0.09; // head travel window on the scrub (compressed
          // so the chain highlight afterwards gets real reading time)
          if (connectors.length) {
            tl.fromTo(connectors,
              {scaleY: 0, opacity: 0},
              {
                scaleY: 1,
                opacity: 1,
                stagger: {each: ZIP_SPAN / Math.max(connectors.length, 1), from: 'start'},
                duration: 0.02,
                ease: 'power2.out',
              },
              ZIP_START + 0.008
            );
          }
          if (slider) {
            // Measure the real teeth stage (layers are visibility:hidden,
            // not display:none, so rects are valid at build time).
            const stage = b2.querySelector(`.${styles.zipperStage}`);
            const b2Rect = b2.getBoundingClientRect();
            const stRect = stage ? stage.getBoundingClientRect() : null;
            const zipFrom = stRect ? stRect.top - b2Rect.top - 46 : -60;
            const zipTo = stRect
              ? stRect.bottom - b2Rect.top - 14
              : (b2.offsetHeight || 400) * 0.92;
            tl.fromTo(slider, {opacity: 0}, {opacity: 1, duration: 0.015}, ZIP_START - 0.004);
            tl.fromTo(slider, {y: zipFrom}, {y: zipTo, duration: ZIP_SPAN, ease: 'none'}, ZIP_START);
          }

          // Connect the dots: after the zip, the three CHAIN rows (the same
          // pairs Beat 3/4 route: fao→dan→spa→que) light amber, with a cue
          // line — separate measured pairs chain into a pathway.
          // Pacing (founder 2026-07-17b: it popped all at once and vanished):
          // the three rows light ONE AT A TIME — a clear top-to-bottom rhythm,
          // each with its own pop — then the cue line arrives, and the whole
          // amber moment HOLDS from ~0.268 to the 0.30 beat exit (~2× the
          // previous on-screen time) so the eye can trace the pathway.
          const chainCue = b2.querySelector(`.${styles.chainCue}`);
          // Colour EVERY pair by its quality tier as the zip head passes — the
          // zipper becomes a quality readout (green = deployable, orange =
          // measured-not-great, red = not reliable). Chain (route) rows also
          // pop. The route's last pair (Español→Runasimi) is red: one bad hop.
          const allRows = Array.from(b2.querySelectorAll(`.${styles.zipperRow}`));
          allRows.forEach((row, ri) => {
            const q = (TEETH[ri] && TEETH[ri].q) || 'ok';
            const {hex, rgb} = QUALITY[q];
            const at = 0.16 + (ri / Math.max(allRows.length - 1, 1)) * 0.085;
            const teethEls = row.querySelectorAll(`.${styles.toothLeft}, .${styles.toothRight}`);
            const conn = row.querySelector(`.${styles.connector}`);
            tl.to(teethEls, {color: hex, duration: 0.006}, at);
            if (conn) {
              tl.to(conn, {backgroundColor: hex, boxShadow: `0 0 10px rgba(${rgb}, 0.8)`, duration: 0.006}, at);
            }
            if (row.classList.contains(styles.zipperRowChain)) {
              tl.fromTo(row, {scale: 1}, {scale: 1.06, duration: 0.005, yoyo: true, repeat: 1, ease: 'power2.out'}, at + 0.004);
            }
          });
          if (chainCue) {
            tl.fromTo(chainCue, {opacity: 0, y: 10}, {opacity: 1, y: 0, duration: 0.018}, 0.268);
          }

          // The headline stitches word by word (the zipper, in type), lands
          // by 0.198, clicks, and holds; the second line springs in under
          // the settled sentence.
          if (narr2L && !stitchIn(narr2L, 0.172, {dur: 0.016, amount: 0.01})) {
            tl.fromTo(narr2L,
              {y: 16, opacity: 0},
              {y: 0, opacity: 1, duration: 0.025, ease: 'power2.out'},
              0.172
            );
          }
          if (narr2R) {
            tl.fromTo(narr2R,
              {y: 16, opacity: 0, scale: 0.96},
              {y: 0, opacity: 1, scale: 1, duration: 0.025, ease: 'back.out(1.4)'},
              0.202
            );
          }
          // House lock-and-pop on the emphasis phrase (green = "measure /
          // deployable"), the instant the headline settles.
          const emph2 = b2.querySelector(`.${styles.narrEmphasis}`);
          if (emph2) {
            addLockPop(gsap, tl, emph2, 0.206, {tone: 'green', chargeDur: 0.004, popDur: 0.004, settleDur: 0.018});
          }

          // Exit.
          tl.to(b2, {autoAlpha: 0, duration: 0.02}, 0.30);
          if (slider) tl.to(slider, {opacity: 0, duration: 0.02}, 0.30);
        }

        // ════════════════════════════════════════════════
        // BEAT 3: THE OPEN MAP — Tier 1 (0.31 — 0.48)
        // The network lights up; at the tail, one chain path highlights
        // as a teaser for the proof in Beat 4.
        // ════════════════════════════════════════════════
        if (b3 && net) {
          // Network rises as Beat 2 fades — cross-dissolve, no dark blink.
          tl.to(b3, {autoAlpha: 1, duration: 0.02}, 0.305);
          tl.fromTo(net,
            {opacity: 0, scale: 0.85},
            {opacity: 1, scale: 1, duration: 0.045, ease: 'power2.out'},
            0.292
          );

          // ── THE MORPH ── the three CHAIN connectors detach from the zipper
          // and fly into the empty map, landing AS the route edges: the pairs
          // we measured become the map's route. Coords measured at build time
          // (layers are visibility:hidden so rects are valid — the slider uses
          // the same trick). Pure fromTo → reversible under scrub.
          const nodeXY = (id) => {
            const nd = NODES.find((x) => x.id === id);
            return nd ? [nd.x, nd.y] : [0, 0];
          };
          // Each chain connector lifts off as a short VERTICAL bar (its zipper
          // shape) from the map's centre — where the zipper sat — then flies
          // and stretches into its diagonal route edge. Fixed viewBox starts:
          // robust, no fragile cross-element DOM measurement (which reads a
          // not-yet-sized SVG at build time).
          const MORPH = [
            {key: 'fao-dan', tier: 'good', start: [352, 150], ends: [nodeXY('fao'), nodeXY('dan')]},
            {key: 'dan-spa', tier: 'ok', start: [356, 216], ends: [nodeXY('dan'), nodeXY('spa')]},
            {key: 'spa-que', tier: 'bad', start: [360, 282], ends: [nodeXY('spa'), nodeXY('que')]},
          ];
          const chainConns = Array.from(
            b2.querySelectorAll(`.${styles.zipperRowChain} .${styles.connector}`),
          );
          MORPH.forEach((m, mi) => {
            const ml = net.querySelector(`[data-morph="${m.key}"]`);
            const realEdge = net.querySelector(`[data-edge="${m.key}"]`);
            if (!ml) return;
            const conn = chainConns[mi];
            const [sx, sy] = m.start;
            const [[ax, ay], [bx, by]] = m.ends;
            const hex = QUALITY[m.tier].hex;
            const at = 0.296 + mi * 0.006;
            if (conn) tl.to(conn, {opacity: 0, duration: 0.004}, at); // lifts off the zipper
            tl.set(ml, {attr: {x1: sx, y1: sy - 16, x2: sx, y2: sy + 16}, stroke: hex, opacity: 1}, at);
            tl.to(ml, {attr: {x1: ax, y1: ay, x2: bx, y2: by}, duration: 0.018, ease: 'power2.inOut'}, at);
            if (realEdge) {
              tl.set(realEdge, {strokeDashoffset: 0, opacity: 0.95, stroke: hex}, at + 0.019);
            }
            tl.to(ml, {opacity: 0, duration: 0.003}, at + 0.019);
          });

          const nodes = net.querySelectorAll(`.${styles.netNode}`);
          if (nodes.length) {
            tl.fromTo(nodes,
              {opacity: 0, scale: 0},
              {opacity: 1, scale: 1, stagger: 0.003, duration: 0.04, ease: 'back.out(1.5)'},
              0.318
            );
          }
          // Non-chain edges draw in around the route (chain edges already
          // arrived via the morph, so exclude them here).
          const edges = net.querySelectorAll(`.${styles.netEdge}:not(.${styles.netEdgeChain})`);
          if (edges.length) {
            tl.fromTo(edges,
              {strokeDashoffset: 300, opacity: 0},
              {strokeDashoffset: 0, opacity: 0.5, stagger: 0.002, duration: 0.04},
              0.335
            );
          }
          const narr3 = b3.querySelector(`.${styles.narrative}`);
          if (narr3) {
            tl.fromTo(narr3, {opacity: 0, y: 16}, {opacity: 1, y: 0, duration: 0.03}, 0.34);
          }
          // Headline stitch rides the container reveal; lands 0.374, clicks,
          // holds through the chain-teaser tail.
          stitchIn(b3.querySelector(`.${styles.narrTitle}`), 0.344, {dur: 0.018, amount: 0.012});

          // Tail: highlight the showcase chain path (fao → dan → spa → que)
          // amber as a "here's one path" teaser into Beat 4.
          const chainIds = ['fao', 'dan', 'spa', 'que'];
          const chainNodeEls = chainIds
            .map(id => net.querySelector(`[data-node="${id}"]`))
            .filter(Boolean);
          const chainEdges = [
            net.querySelector(`[data-edge="fao-dan"]`),
            net.querySelector(`[data-edge="dan-spa"]`),
            net.querySelector(`[data-edge="spa-que"]`),
          ].filter(Boolean);

          // Trace the route: nodes flash white; each hop KEEPS its quality
          // colour and gains a glow in that colour — so the green→orange→RED
          // route reads its weakest (red) hop at a glance.
          const CHAIN_TIER = {'fao-dan': 'good', 'dan-spa': 'ok', 'spa-que': 'bad'};
          chainNodeEls.forEach((node) => {
            const c = node.querySelector('circle');
            if (c) tl.to(c, {fill: '#ffffff', stroke: '#ffffff', r: 7, duration: 0.02}, 0.42);
          });
          chainEdges.forEach((edge, i) => {
            const hex = tierHex(CHAIN_TIER[edge.getAttribute('data-edge')] || 'ok');
            tl.to(edge, {
              opacity: 1,
              strokeWidth: 3,
              filter: `drop-shadow(0 0 6px ${hex})`,
              duration: 0.025,
            }, 0.42 + i * 0.01);
          });

          // Exit narrative + the whole network (Beat 4 is the close-up).
          tl.to(b3, {autoAlpha: 0, duration: 0.02}, 0.46);
          tl.to(net, {opacity: 0, duration: 0.03}, 0.465);
        }

        // ════════════════════════════════════════════════
        // BEAT 4: TRACEABLE & REAL — the chain proof (0.48 — 0.66)
        // The highlighted path unrolls into readable hops with the
        // corpus that bridges each one; the last hop self-corrects and
        // the score climbs — proof we actually measure quality.
        // ════════════════════════════════════════════════
        if (b4) {
          // Bubbles enter as Beat 3's network fades out — cross-dissolve.
          tl.to(b4, {autoAlpha: 1, duration: 0.02}, 0.462);

          const bubbles = b4.querySelectorAll(`.${styles.hopBubble}`);
          const arrows = b4.querySelectorAll(`.${styles.hopArrow}`);

          if (bubbles.length) {
            tl.fromTo(bubbles,
              {y: 40, opacity: 0, scale: 0.85},
              {y: 0, opacity: 1, scale: 1, stagger: 0.015, duration: 0.05, ease: 'back.out(1.4)'},
              0.47
            );
          }
          if (arrows.length) {
            tl.fromTo(arrows,
              {opacity: 0, x: -5},
              {opacity: 0.7, x: 0, stagger: 0.015, duration: 0.04},
              0.485
            );
          }

          const bridges = b4.querySelectorAll(`.${styles.bridgeLabel}`);
          if (bridges.length) {
            tl.fromTo(bridges,
              {y: 10, opacity: 0, scale: 0.9},
              {y: 0, opacity: 1, scale: 1, stagger: 0.015, duration: 0.04, ease: 'power2.out'},
              0.50
            );
          }

          const narr4 = b4.querySelector(`.${styles.narrative}`);
          if (narr4) {
            tl.fromTo(narr4, {y: 20, opacity: 0}, {y: 0, opacity: 1, duration: 0.04}, 0.52);
          }

          // ── Correction pulse on the last hop (Quechua) ──
          // Resolves by ~0.62 and HOLDS to the exit (0.655) so a human
          // scrolling at normal speed sees the corrected text + climbed score.
          const lastBubble = b4.querySelector('[data-last]');
          const roughScore = b4.querySelector(`.${styles.scoreChip}`);
          const improvedScore = b4.querySelector(`.${styles.scoreImproved}`);

          if (lastBubble) {
            tl.to(lastBubble, {
              borderColor: 'rgba(232, 179, 57, 0.6)',
              boxShadow: '0 0 20px rgba(232, 179, 57, 0.2), inset 0 0 15px rgba(232, 179, 57, 0.05)',
              duration: 0.02,
              ease: 'power2.in',
            }, 0.55);
            tl.to(lastBubble, {x: 3, duration: 0.005}, 0.555);
            tl.to(lastBubble, {x: -3, duration: 0.005}, 0.56);
            tl.to(lastBubble, {x: 0, duration: 0.005}, 0.565);

            const roughText = lastBubble.querySelector(`.${styles.hopTextRough}`);
            const fixedText = lastBubble.querySelector(`.${styles.hopTextFixed}`);

            if (roughText) {
              tl.to(roughText, {
                opacity: 0.3,
                color: '#f08a93',
                textDecoration: 'line-through',
                duration: 0.02,
              }, 0.57);
              tl.to(roughText, {opacity: 0, height: 0, marginTop: 0, duration: 0.015}, 0.585);
            }
            if (fixedText) {
              tl.fromTo(fixedText,
                {opacity: 0, height: 0},
                {opacity: 1, height: 'auto', duration: 0.025, ease: 'power2.out'},
                0.59
              );
            }
            tl.to(lastBubble, {
              borderColor: 'rgba(76, 175, 80, 0.4)',
              boxShadow: '0 0 20px rgba(76, 175, 80, 0.15), inset 0 0 15px rgba(76, 175, 80, 0.05)',
              duration: 0.02,
            }, 0.6);
          }
          if (roughScore) {
            tl.to(roughScore, {opacity: 0, scale: 0.8, height: 0, duration: 0.015}, 0.585);
          }
          if (improvedScore) {
            tl.fromTo(improvedScore,
              {opacity: 0, scale: 0.6, height: 0},
              {opacity: 1, scale: 1, height: 'auto', duration: 0.025, ease: 'back.out(2.5)'},
              0.6
            );
          }

          tl.to(b4, {autoAlpha: 0, duration: 0.02}, 0.66);
        }

        // ════════════════════════════════════════════════
        // BEAT 5: THE SEAL — Tier 2, the apex (0.66 — 0.84)
        // A community's sealed test set certifies a method without anyone
        // — not even us — ever seeing the data. The method travels in;
        // only a score returns.
        // ════════════════════════════════════════════════
        if (b5) {
          tl.to(b5, {autoAlpha: 1, duration: 0.02}, 0.665);

          const kicker5 = b5.querySelector(`.${styles.kicker}`);
          const vault = b5.querySelector(`.${styles.sealVault}`);
          const bars = b5.querySelectorAll(`.${styles.sealBar}`);
          const method = b5.querySelector(`.${styles.sealMethod}`);
          const arrowIn = b5.querySelector(`.${styles.sealArrowIn}`);
          const arrowOut = b5.querySelector(`.${styles.sealArrowOut}`);
          const score = b5.querySelector(`.${styles.sealScore}`);
          const lock = b5.querySelector(`.${styles.sealLock}`);
          const keys = b5.querySelector(`.${styles.sealKeys}`);
          const narr5 = b5.querySelector(`.${styles.narrative}`);

          if (kicker5) {
            tl.fromTo(kicker5, {opacity: 0, y: -10}, {opacity: 1, y: 0, duration: 0.02}, 0.67);
          }
          // Vault rises first — the sealed data.
          if (vault) {
            tl.fromTo(vault,
              {opacity: 0, scale: 0.9, y: 16},
              {opacity: 1, scale: 1, y: 0, duration: 0.035, ease: 'power2.out'},
              0.672
            );
          }
          if (bars.length) {
            tl.fromTo(bars,
              {opacity: 0, scaleX: 0.6, transformOrigin: 'left center'},
              {opacity: 1, scaleX: 1, stagger: 0.006, duration: 0.025, ease: 'power1.out'},
              0.685
            );
          }
          if (keys) {
            tl.fromTo(keys, {opacity: 0}, {opacity: 1, duration: 0.02}, 0.693);
          }
          // The method arrives from the left and travels to the data.
          if (method) {
            tl.fromTo(method,
              {opacity: 0, x: -50, scale: 0.9},
              {opacity: 1, x: 0, scale: 1, duration: 0.03, ease: 'power2.out'},
              0.70
            );
          }
          if (arrowIn) {
            const trackIn = arrowIn.querySelector(`.${styles.sealArrowTrack}`);
            tl.fromTo(arrowIn, {opacity: 0}, {opacity: 1, duration: 0.015}, 0.713);
            if (trackIn) {
              tl.fromTo(trackIn,
                {scaleX: 0, transformOrigin: 'left center'},
                {scaleX: 1, duration: 0.025, ease: 'power1.inOut'},
                0.713
              );
            }
          }
          // Authorization "click" — the lock glows, then settles.
          if (lock) {
            tl.to(lock, {
              filter: 'drop-shadow(0 0 10px rgba(232,179,57,0.8))',
              duration: 0.015,
            }, 0.73);
            tl.to(lock, {filter: 'drop-shadow(0 0 3px rgba(232,179,57,0.35))', duration: 0.02}, 0.752);
          }
          // Only a score returns.
          if (arrowOut) {
            const trackOut = arrowOut.querySelector(`.${styles.sealArrowTrack}`);
            tl.fromTo(arrowOut, {opacity: 0}, {opacity: 1, duration: 0.015}, 0.735);
            if (trackOut) {
              tl.fromTo(trackOut,
                {scaleX: 0, transformOrigin: 'left center'},
                {scaleX: 1, duration: 0.025, ease: 'power1.inOut'},
                0.735
              );
            }
          }
          if (score) {
            tl.fromTo(score,
              {opacity: 0, x: 40, scale: 0.7},
              {opacity: 1, x: 0, scale: 1, duration: 0.03, ease: 'back.out(2)'},
              0.748
            );
          }
          if (narr5) {
            tl.fromTo(narr5, {y: 20, opacity: 0}, {y: 0, opacity: 1, duration: 0.035}, 0.753);
          }
          stitchIn(b5.querySelector(`.${styles.narrTitle}`), 0.757, {dur: 0.018, amount: 0.012});

          // Exit — overlaps Beat 6's entrance for a seamless cross-fade.
          tl.to(b5, {autoAlpha: 0, duration: 0.025}, 0.835);
        }

        // ════════════════════════════════════════════════
        // BEAT 6: THE MISSION — help us build (0.84 — 1.0)
        // Network returns as a dim constellation; logo, mission line,
        // values, live stats and CTA settle in. Slimmed to fit 100vh.
        // ════════════════════════════════════════════════
        if (b6) {
          // Enter while Beat 5 is still fading — no dark gap at the handoff.
          tl.to(b6, {autoAlpha: 1, duration: 0.03}, 0.836);

          if (net) {
            const allNodes6 = net.querySelectorAll(`.${styles.netNode}`);
            const allEdges6 = net.querySelectorAll(`.${styles.netEdge}`);
            tl.to(allNodes6, {opacity: 0.45, duration: 0.02}, 0.84);
            tl.to(allEdges6, {opacity: 0.12, stroke: '#4dd8ff', strokeWidth: 1, filter: 'none', duration: 0.02}, 0.84);
            tl.to(net, {opacity: 0.22, duration: 0.04}, 0.844);
          }

          const logoWrap = b6.querySelector(`.${styles.logoReveal}`);
          if (logoWrap) {
            tl.fromTo(logoWrap,
              {y: -24, opacity: 0, scale: 0.85},
              {y: 0, opacity: 1, scale: 1, duration: 0.03, ease: 'back.out(1.5)'},
              0.85
            );
          }

          const missionTitle = b6.querySelector(`.${styles.missionTitle}`);
          const missionSub = b6.querySelector(`.${styles.missionSub}`);
          if (missionTitle) {
            tl.fromTo(missionTitle, {y: 18, opacity: 0}, {y: 0, opacity: 1, duration: 0.03, ease: 'power2.out'}, 0.858);
          }
          // The accent line lands letter by letter (beat 6's springy voice),
          // clicks at 0.898, and holds through the mission assembly.
          stitchIn(b6.querySelector(`.${styles.missionTitleAccent}`), 0.864, {
            unit: 'chars',
            dur: 0.02,
            amount: 0.014,
            ease: 'back.out(1.6)',
          });
          if (missionSub) {
            tl.fromTo(missionSub, {y: 14, opacity: 0}, {y: 0, opacity: 1, duration: 0.03}, 0.868);
          }

          const badges = b6.querySelectorAll(`.${styles.valueBadge}`);
          if (badges.length) {
            tl.fromTo(badges,
              {y: 18, opacity: 0, scale: 0.92},
              {y: 0, opacity: 1, scale: 1, stagger: 0.008, duration: 0.03, ease: 'back.out(1.2)'},
              0.878
            );
          }

          const statsWrap = b6.querySelector(`.${styles.statsWrap}`);
          if (statsWrap) {
            tl.fromTo(statsWrap, {y: 14, opacity: 0}, {y: 0, opacity: 1, duration: 0.03, ease: 'power2.out'}, 0.895);
          }

          const cta = b6.querySelector(`.${styles.ctaButton}`);
          if (cta) {
            tl.fromTo(cta,
              {scale: 0.9, opacity: 0},
              {scale: 1, opacity: 1, duration: 0.03, ease: 'back.out(1.5)'},
              0.91
            );
          }

          // Trailing hold — a no-op tween that extends the timeline past the
          // CTA so the fully-assembled mission (CTA included) holds on screen
          // through the end of the scroll, instead of the CTA only landing on
          // the very last frame before the section unpins.
          tl.to(b6, {autoAlpha: 1, duration: 0.07}, 0.96);
        }
      }, seam);

      // The layout above the seam settles late (hero two-phase unmount, live
      // stats, web fonts). Re-measure once the next frame paints so start/end
      // reflect the real page, never a mid-hydration snapshot — otherwise the
      // pin can end up with zero scroll distance and the beats never play.
      requestAnimationFrame(() => {
        if (!cancelled) ScrollTrigger.refresh();
      });
    });

    return () => {
      cancelled = true;
      if (ctx) ctx.revert();
      // SplitText mutates React-rendered DOM — restore the original nodes
      // AFTER the tweens revert, or React 19 teardown can throw.
      for (const sp of splits) {
        try {
          sp.revert();
        } catch (e) {
          /* already reverted */
        }
      }
      splits.length = 0;
    };
  }, [reduced]);

  // ── Reduced-motion fallback ──
  if (reduced) {
    return (
      <section className={clsx('labV4', styles.seam, styles.reducedWrap)}>
        <div className={styles.reducedPanel}>
          <h2 className={styles.reducedTitle}>How Champollion works</h2>
          <p className={styles.reducedSub}>
            Champollion is open infrastructure to support communities building
            machine translation for their own languages.
          </p>
          <p className={styles.reducedSub}>
            The race in machine translation is to build one model that speaks
            every language. Every major service and model combined — Google,
            Microsoft, NLLB, DeepL and the rest — covers{' '}
            {MONO ? (MONO.coveredLiving || 383).toLocaleString('en-US') : '383'} of the{' '}
            {MONO ? (MONO.livingTotal || 7077).toLocaleString('en-US') : '7,077'} living
            languages — the rest have nothing. And a language isn't a dataset —
            it's a living system, and it belongs to the people who speak it.
          </p>
          <p className={styles.reducedSub}>
            So Champollion measures instead. Every method — human or machine —
            is scored on a real test set, pair by pair. Each measured pair lights
            up an <strong>open map</strong>: who can translate what, how good each
            method is, and where the gaps are.
          </p>
          <p className={styles.reducedSub}>
            Every score traces back to a licensed corpus — no scraped black boxes.
          </p>
          <p className={styles.reducedSub}>
            <strong>The highest standard is sealed.</strong> A community keeps its
            own secret test set and holds the keys. They authorize a method to be
            scored against it — the method comes to the data, and only the score
            comes back. No one, not even Champollion, sees the data.
          </p>
          <p className={styles.reducedSub}>
            <strong>The mission:</strong> every language into every language —
            under terms its people set.
          </p>
          <p className={styles.reducedSub}>
            <em>Showcase chain:</em>{' '}
            Føroysk → Dansk → Español → Runasimi (Quechua)
          </p>
          <ul className={styles.reducedPairs}>
            {CHAIN_PHRASE.hops.map(h => (
              <li key={h.code} className={styles.reducedPair}>
                <strong>{h.lang}</strong>
                <span className={styles.reducedArrow}> → </span>
                {h.textFixed || h.text}
              </li>
            ))}
          </ul>
        </div>
      </section>
    );
  }

  // ── Full animated render ──
  return (
    <section ref={seamRef} className={clsx('labV4', styles.seam)}>
      <div className={styles.seamInner}>

        {/* ── SLIDE 0: The project statement (moved out of the hero) ── */}
        <div ref={beat0Ref} className={clsx(styles.beatLayer, styles.openerLayer)}>
          <div className={styles.opener}>
            <h2 className={styles.openerTitle}>
              Champollion is open infrastructure to support communities
              building machine translation for their own languages.
            </h2>
            <p className={styles.openerSub}>
              Here's the problem it exists to solve.
            </p>
          </div>
        </div>

        {/* ── BEAT 1: The Problem — centralized MT, combined ── */}
        <div ref={beat1Ref} className={styles.beatLayer}>
          {MONO_FIELD ? (
            /* REAL data: NLLB-200's covered languages (teal) against the
               living-language field (ember = not covered). Positions are the
               hero map's real layout, sampled + normalized at build time
               (poster.monolith, generateGraphJson v10). Cohort <g>s keep the
               scrub to ~10 group tweens — never per-dot animation. */
            <svg
              className={styles.monolithSvg}
              viewBox={`0 0 ${MONO.box[0]} ${MONO.box[1]}`}
              aria-hidden="true"
            >
              {MONO_FIELD.cohorts.map((pts, ci) => (
                <g key={ci} className={styles.fieldCohort}>
                  {pts.map(([x, y], i) => (
                    <circle
                      key={i}
                      cx={x}
                      cy={y}
                      r={1.7}
                      className={clsx(styles.fieldDot, i % 2 === 1 && styles.fieldDotSlim)}
                    />
                  ))}
                </g>
              ))}
              <g className={styles.fieldCovered}>
                {MONO_FIELD.covered.map(([x, y], i) => (
                  <circle
                    key={i}
                    cx={x}
                    cy={y}
                    r={2.2}
                    className={clsx(styles.fieldDotCovered, i < 40 && styles.fieldSparkle)}
                  />
                ))}
              </g>
              <circle className={styles.monolith} cx={300} cy={200} r={62} />
              <text className={styles.monolithLabel} x={300} y={190} textAnchor="middle">
                EVERY MAJOR
              </text>
              <text className={styles.monolithLabel} x={300} y={208} textAnchor="middle">
                TRANSLATOR
              </text>
              <text className={styles.monolithSubLabel} x={300} y={228} textAnchor="middle">
                combined
              </text>
            </svg>
          ) : (
            /* LEGACY decorative spokes — stale poster without `monolith`. */
            <svg className={styles.monolithSvg} viewBox="0 0 600 400" aria-hidden="true">
              {SPOKES.map((s, i) => (
                <React.Fragment key={i}>
                  <line
                    className={clsx(styles.spoke, s.dim && styles.spokeDim)}
                    x1={300} y1={200} x2={s.x} y2={s.y}
                  />
                  <text
                    className={clsx(styles.spokeLabel, s.dim && styles.spokeLabelDim)}
                    x={s.x} y={s.y - 8}
                    textAnchor="middle"
                  >
                    {s.lang}
                  </text>
                </React.Fragment>
              ))}
              <circle className={styles.monolith} cx={300} cy={200} r={50} />
              <text className={styles.monolithLabel}
                    x={300} y={204} textAnchor="middle">
                1 MODEL
              </text>
            </svg>
          )}
          {/* Narrative (bottom-left). */}
          <div className={clsx(styles.narrative, styles.narrativeLeft)}>
            <span className={clsx(styles.kicker, styles.kickerProblem)}>
              The problem
            </span>
            <h2 className={styles.narrTitle}>
              The race in machine translation is to build one model
              that speaks every language.
            </h2>
            <p className={styles.narrSub}>
              But a language isn't a dataset. It's a living system —
              with grammar, nuance, and soul — and it belongs to the
              people who speak it.
            </p>
            {MONO_FIELD && (
              <>
                <p className={styles.fieldStat}>
                  <Tip {...MONO_TIP} className={styles.chipTip}>
                    <span>
                      Google, Microsoft, NLLB, DeepL — every major service and
                      model <strong>combined</strong> covers{' '}
                      <strong>{(MONO.coveredLiving || 0).toLocaleString('en-US')}</strong> of the{' '}
                      <strong>{(MONO.livingTotal || 7077).toLocaleString('en-US')}</strong>{' '}
                      living languages.
                    </span>
                  </Tip>
                </p>
                <div className={styles.fieldLegend} aria-hidden="true">
                  <span className={styles.fieldLegendItem}>
                    <i className={styles.fieldSwatchCovered} />
                    covered by at least one
                  </span>
                  <span className={styles.fieldLegendItem}>
                    <i className={styles.fieldSwatchEmber} />
                    {(MONO.uncoveredTotal || 0).toLocaleString('en-US')}{' '}
                    living languages · covered by none
                  </span>
                </div>
              </>
            )}
          </div>
        </div>

        {/* ── BEAT 2: Measure Every Method ── */}
        <div ref={beat2Ref} className={styles.beatLayer}>
          {/* Zipper teeth. Chain rows carry the class the tail highlight
              targets — the same pairs Beat 3/4 route. */}
          <div className={styles.zipperStage}>
            {TEETH.map((t, i) => (
              <div key={i} className={clsx(styles.zipperRow, t.chain && styles.zipperRowChain)}>
                <span className={styles.toothLeft}>{t.l}</span>
                <span className={styles.connector} />
                <span className={styles.toothRight}>{t.r}</span>
              </div>
            ))}
          </div>
          {/* Champollion logo slider — travels down the center line. */}
          <div ref={sliderRef} className={styles.slider}>
            <BrandMark size={36} />
          </div>
          {/* One cohesive statement, centered beneath the zipper. (Replaces the
              old far-corner left/right split, which read as two disconnected
              fragments the eye had to jump between.) The two lines still reveal
              in sequence as the slider zips down. */}
          <div className={clsx(styles.narrative, styles.narrativeStitch)}>
            <h2 className={styles.stitchLine1}>
              So we don&rsquo;t pick a winner.{' '}
              <span className={styles.narrEmphasis}>We measure.</span>
            </h2>
            <p className={styles.stitchLine2}>
              Every method — human or machine — scored pair by pair.
            </p>
            {/* Connect-the-dots cue: the amber rows are Beat 3/4's pathway. */}
            <p className={styles.chainCue}>
              …and separate pairs chain into a pathway: Føroysk → Dansk →
              Español → Runasimi
            </p>
          </div>
        </div>

        {/* ── NETWORK SVG (Beat 3 map + Beat 6 backdrop) ── */}
        <svg ref={networkRef} className={styles.networkSvg}
             viewBox="0 0 700 440" aria-hidden="true">
          {/* Edges. */}
          {EDGES.map(([from, to], i) => {
            const a = NODES.find(n => n.id === from);
            const b = NODES.find(n => n.id === to);
            if (!a || !b) return null;
            const isChain =
              (from === 'fao' && to === 'dan') ||
              (from === 'dan' && to === 'spa') ||
              (from === 'spa' && to === 'que');
            return (
              <line key={i}
                className={clsx(styles.netEdge, isChain && styles.netEdgeChain)}
                data-edge={isChain ? `${from}-${to}` : undefined}
                style={{stroke: tierHex(edgeTier(from, to, i))}}
                x1={a.x} y1={a.y} x2={b.x} y2={b.y}
              />
            );
          })}
          {/* Morph flight lines — at the Beat-2→3 transition the CHAIN
              connectors detach from the zipper, fly, and land AS these three
              route edges (coords + colour set at build time). Hidden at rest. */}
          {['fao-dan', 'dan-spa', 'spa-que'].map((key) => (
            <line key={key} data-morph={key} className={styles.morphLine} />
          ))}
          {/* Nodes. */}
          {NODES.map(n => (
            <g key={n.id}
               className={clsx(
                 styles.netNode,
                 n.hub && styles.netNodeHub,
                 n.chain && styles.netNodeChain,
               )}
               data-node={n.id}>
              <circle cx={n.x} cy={n.y} r={n.hub ? 6 : n.chain ? 5 : 4} />
              <text className={styles.netLabel}
                    x={n.x} y={n.y + 17} textAnchor="middle">
                {n.label}
              </text>
            </g>
          ))}
        </svg>

        {/* ── BEAT 3: The Open Map (narrative overlay) ── */}
        <div ref={beat3Ref} className={styles.beatLayer}>
          <div className={styles.narrative}>
            <span className={clsx(styles.kicker, styles.kickerOpen)}>
              Tier 1 · Open Benchmarks
            </span>
            <h2 className={styles.narrTitle}>
              Every measured pair lights up the map.
            </h2>
            <p className={styles.narrSub}>
              Open test sets, every method ranked, every gap visible — so
              anyone can see who can translate what, and how well. Chains link
              languages that were never paired directly.
            </p>
          </div>
        </div>

        {/* ── BEAT 4: Traceable & Real (the chain proof) ── */}
        <div ref={beat4Ref} className={clsx(styles.beatLayer, styles.chainOverlay)}>
          {/* Chain pipeline with corpus bridge labels between bubbles. */}
          <div className={styles.chainFlow}>
            {CHAIN_PHRASE.hops.map((hop, i) => (
              <React.Fragment key={hop.code}>
                {/* Bridge label (corpus metadata) between hops. */}
                {i > 0 && (
                  <div className={styles.bridgeWrap}>
                    <span className={styles.hopArrow}>→</span>
                    <div className={styles.bridgeLabel}>
                      <span className={styles.bridgeCorpus}>
                        {CHAIN_PHRASE.bridges[i - 1].corpus}
                      </span>
                      <span className={styles.bridgeMeta}>
                        {CHAIN_PHRASE.bridges[i - 1].pairs} pairs · {CHAIN_PHRASE.bridges[i - 1].license}
                      </span>
                      <span className={styles.bridgeQuality}>
                        {CHAIN_PHRASE.bridges[i - 1].quality}
                      </span>
                    </div>
                  </div>
                )}
                <div className={styles.hopBubble}
                     data-last={hop.code === 'que' ? '' : undefined}>
                  <span className={styles.hopLang}>{hop.lang}</span>
                  <span className={styles.hopLangEn}>{hop.langEn}</span>
                  {/* Translation text. For Quechua: rough first, then corrected. */}
                  {hop.textRough ? (
                    <>
                      <span className={styles.hopTextRough}>{hop.textRough}</span>
                      <span className={styles.hopTextFixed}>
                        {hop.textFixed}
                      </span>
                    </>
                  ) : (
                    <span className={styles.hopTextRough}>{hop.text}</span>
                  )}
                  {/* Score chip — only on last hop. chrF++ on sacrebleu's
                      0–100 scale (site-wide convention), with a plain-language
                      Tip on hover/focus since this is the first score a
                      visitor meets. */}
                  {hop.code === 'que' && (
                    <>
                      <Tip {...CHRF_TIP} className={styles.chipTip}>
                        <span className={styles.scoreChip}>chrF++ 24</span>
                      </Tip>
                      <Tip {...CHRF_TIP} className={styles.chipTip}>
                        <span className={styles.scoreImproved}>
                          chrF++ 71{' '}
                          <span className={styles.scoreDelta}>↑ +47</span>
                        </span>
                      </Tip>
                    </>
                  )}
                </div>
              </React.Fragment>
            ))}
          </div>
          {/* Narrative below the chain (in-flow, sits with the bubbles). */}
          <div className={clsx(styles.narrative, styles.narrativeInline)}>
            <h2 className={styles.narrTitle}>
              Every score traces back to a licensed corpus.
            </h2>
            <p className={styles.narrSub}>
              From the Faroe Islands to the Andes — real, licensed corpora,
              auditable hop by hop. No scraped black boxes. Scores are chrF++
              on a 0–100 scale, higher is better. (The chain shown is an
              illustration of how routing and coaching work.)
            </p>
          </div>
        </div>

        {/* ── BEAT 5: The Seal (Tier 2 — the sovereign apex) ── */}
        <div ref={beat5Ref} className={clsx(styles.beatLayer, styles.sealOverlay)}>
          <div className={styles.sealStage}>
            {/* The method — travels to the data. */}
            <div className={styles.sealMethod}>
              <span className={styles.sealMethodIcon} aria-hidden="true">⌘</span>
              <span className={styles.sealMethodTitle}>a method</span>
              <span className={styles.sealMethodSub}>human or machine</span>
            </div>

            {/* Arrow IN. */}
            <div className={styles.sealArrowIn}>
              <span className={styles.sealArrowTrack}>
                <span className={styles.sealArrowLine} />
                <span className={styles.sealArrowHead}>▶</span>
              </span>
              <span className={styles.sealArrowCap}>comes to the data</span>
            </div>

            {/* The sealed vault — the community's secret test set. */}
            <div className={styles.sealVault}>
              <div className={styles.sealVaultHead}>
                <svg className={styles.sealLock} viewBox="0 0 24 24" aria-hidden="true">
                  <rect x="5" y="10.5" width="14" height="10" rx="2"
                        fill="rgba(232,179,57,0.14)" stroke="#e8b339" strokeWidth="1.4" />
                  <path d="M8 10.5 V8 a4 4 0 0 1 8 0 V10.5"
                        fill="none" stroke="#e8b339" strokeWidth="1.4" />
                  <circle cx="12" cy="15" r="1.5" fill="#e8b339" />
                </svg>
                <div className={styles.sealVaultHeadText}>
                  <span className={styles.sealVaultTitle}>Sealed test set</span>
                  <span className={styles.sealVaultOwner}>held by the community</span>
                </div>
              </div>
              <div className={styles.sealRedacted} aria-hidden="true">
                <span className={styles.sealBar} style={{width: '92%'}} />
                <span className={styles.sealBar} style={{width: '74%'}} />
                <span className={styles.sealBar} style={{width: '86%'}} />
                <span className={styles.sealBar} style={{width: '62%'}} />
              </div>
              <div className={styles.sealKeys}>
                <span className={styles.sealKeyDots} aria-hidden="true">
                  <i /><i /><i /><i /><i />
                </span>
                <span className={styles.sealKeysLabel}>community holds the keys</span>
              </div>
            </div>

            {/* Arrow OUT. */}
            <div className={styles.sealArrowOut}>
              <span className={styles.sealArrowTrack}>
                <span className={styles.sealArrowLine} />
                <span className={styles.sealArrowHead}>▶</span>
              </span>
              <span className={styles.sealArrowCap}>only a score returns</span>
            </div>

            {/* The score that comes back — 0–100 scale, and NOT "certified":
                no sealed-set run has published yet, so the chip stays an
                illustration (disclaimer in the narrative below). */}
            <div className={styles.sealScore}>
              <span className={styles.sealScoreVal}>81</span>
              <Tip {...CHRF_TIP} className={styles.chipTip}>
                <span className={styles.sealScoreLabel}>chrF++ · 0–100</span>
              </Tip>
            </div>
          </div>

          {/* Narrative below the seal. */}
          <div className={clsx(styles.narrative, styles.narrativeInline)}>
            <span className={clsx(styles.kicker, styles.kickerSeal)}>
              Tier 2 · Sovereign
            </span>
            <h2 className={styles.narrTitle}>
              The highest standard is one we never see.
            </h2>
            <p className={styles.narrSub}>
              A community keeps its own secret test set and holds the keys.
              They authorize a method to be scored against it — the method
              comes to the data, and only the score comes back. (Illustration:
              sealed-set scores appear on the public board once communities
              run them.)
            </p>
          </div>
        </div>

        {/* ── BEAT 6: The Mission ── */}
        <div ref={beat6Ref} className={clsx(styles.beatLayer, styles.missionLayer)}>
          {/* Logo. */}
          <div className={styles.logoReveal}>
            <BrandMark size={52} />
          </div>
          {/* Mission headline. */}
          <h2 className={styles.missionTitle}>
            Every language into every language —
            <br />
            <span className={styles.missionTitleAccent}>under terms its people set.</span>
          </h2>
          <p className={styles.missionSub}>
            Speakers are the solution. In the age of AI, the bleeding edge of
            machine translation will be built by the communities who speak the
            language — maybe yours.
          </p>
          {/* Values badges. */}
          <div className={styles.valuesRow}>
            <div className={styles.valueBadge}>
              <span className={styles.valueIcon}>🏛️</span>
              <span className={styles.valueText}>Sovereignty-Aspirant</span>
              <span className={styles.valueSub}>Indigenous data sovereignty</span>
            </div>
            <div className={styles.valueBadge}>
              <span className={styles.valueIcon}>🔓</span>
              <span className={styles.valueText}>Source-Available</span>
              <span className={styles.valueSub}>PolyForm NC + AGPL · GitHub</span>
            </div>
            <div className={styles.valueBadge}>
              <span className={styles.valueIcon}>🤝</span>
              <span className={styles.valueText}>Community-Led</span>
              <span className={styles.valueSub}>Corpora by partnership</span>
            </div>
            <div className={styles.valueBadge}>
              <span className={styles.valueIcon}>⌨️</span>
              <span className={styles.valueText}>CLI-First</span>
              <span className={styles.valueSub}>npx champollion run</span>
            </div>
          </div>
          {/* Stats — REAL live progress, stated with ambition. */}
          <div className={styles.statsWrap}>
            <div className={styles.statsAim}>Toward every language, by every method</div>
            <div className={styles.statsRow}>
              {buildPlatformStats(stats).map((stat, i) => (
                <React.Fragment key={stat.label}>
                  {i > 0 && <div className={styles.statDivider} />}
                  <div className={styles.statItem}>
                    <span className={styles.statNumber}>{stat.number}</span>
                    <span className={styles.statLabel}>{stat.label}</span>
                  </div>
                </React.Fragment>
              ))}
            </div>
          </div>
          {/* CTA. */}
          <a href="/contribute" className={styles.ctaButton}>
            Start Contributing
          </a>
        </div>
      </div>
    </section>
  );
}
