/**
 * Integrity checks for the bulk external MT results index
 * (shared/catalogue/external-mt-index.json) — the machine-derived sibling of
 * the curated external-results.json tier. Structural invariants only (the file
 * is generated by arena/scripts/import_opus_mt_leaderboard.py, so a schema
 * drift here means the importer changed without this contract following):
 *
 *   - commit-pinned provenance carrying champollion-derived + upstream credit
 *   - every testset used under pairs has a contamination_posture note
 *     (relative-only honesty is non-optional)
 *   - every metric used under pairs is declared in metrics
 *   - model indices resolve into the models table; values are finite numbers
 *     on the declared 0-100 scales
 *
 * Skips when the index is absent (cli-only / packaged checkouts — the file is
 * monorepo-tracked and deliberately NOT bundled into the npm package).
 */

import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MONO = path.resolve(__dirname, '..', '..');
const INDEX_FILE = path.join(MONO, 'shared', 'catalogue', 'external-mt-index.json');

const present = fs.existsSync(INDEX_FILE);

test('external-mt-index (bulk publicly-reported results)', { skip: !present && 'index not present (cli-only checkout)' }, async (t) => {
  const idx = JSON.parse(fs.readFileSync(INDEX_FILE, 'utf8'));

  await t.test('carries pinned, credited, champollion-derived provenance', () => {
    assert.ok(idx.version >= 2);
    assert.equal(typeof idx.provider, 'string');
    assert.ok(Array.isArray(idx.sources) && idx.sources.length >= 2,
      'both Helsinki leaderboards must be pinned');
    for (const src of idx.sources) {
      assert.match(src.commit, /^[0-9a-f]{40}$/, `${src.name}: commit must be a full upstream SHA`);
      assert.match(src.retrieved, /^\d{4}-\d{2}-\d{2}$/);
      assert.ok(src.license, `${src.name}: upstream license must be recorded`);
      assert.ok(src.credit.length >= 10, `${src.name}: upstream credit must be recorded (always-cite-work)`);
      assert.ok(Array.isArray(src.model_id_prefixes) && src.model_id_prefixes.length > 0,
        `${src.name}: model_id_prefixes must map cells back to this leaderboard`);
    }
    assert.match(idx.provenance, /champollion-derived/,
      'the best-per-pair selection is a Champollion derivation and must say so');
    assert.match(idx.provenance, /derived from/,
      'provenance must name the upstreams');
  });

  await t.test('every model resolves to a provider family (no unknowns)', () => {
    const prefixes = Object.keys(idx.family_derivation).sort((a, b) => b.length - a.length);
    const orphans = idx.models.filter((m) => !prefixes.some((p) => m.startsWith(p)));
    assert.deepEqual(orphans.slice(0, 5), [],
      `${orphans.length} model id(s) match no family_derivation prefix`);
  });

  await t.test('every used testset has a contamination posture note', () => {
    const used = new Set();
    for (const perPair of Object.values(idx.pairs)) {
      for (const ts of Object.keys(perPair)) used.add(ts);
    }
    assert.ok(used.size > 0, 'index must not be empty');
    for (const ts of used) {
      assert.ok(
        typeof idx.contamination_posture[ts] === 'string' && idx.contamination_posture[ts].length >= 10,
        `testset '${ts}' is used but has no contamination_posture note`,
      );
    }
  });

  await t.test('cells resolve: declared metrics, in-range model indices, sane values', () => {
    const metricIds = new Set(Object.keys(idx.metrics));
    const nModels = idx.models.length;
    assert.ok(nModels > 0);
    let cells = 0;
    for (const [pair, perPair] of Object.entries(idx.pairs)) {
      // 2-4 letter codes: upstream mixes ISO 639-1/-3 with a few legacy 4-letter
      // ids (e.g. 'toki'), plus optional _Script suffixes (e.g. srp_Cyrl).
      assert.match(pair, /^[a-z]{2,4}(_[A-Za-z0-9]+)?-[a-z]{2,4}(_[A-Za-z0-9]+)?$/,
        `pair key '${pair}' is not 'src-tgt'`);
      for (const perTs of Object.values(perPair)) {
        for (const [metric, cell] of Object.entries(perTs)) {
          cells += 1;
          assert.ok(metricIds.has(metric), `undeclared metric '${metric}' on ${pair}`);
          const [mi, value] = cell;
          assert.ok(Number.isInteger(mi) && mi >= 0 && mi < nModels,
            `model index ${mi} out of range on ${pair}`);
          assert.ok(Number.isFinite(value) && value >= 0 && value <= 100,
            `value ${value} out of the 0-100 scale on ${pair}/${metric}`);
        }
      }
    }
    assert.ok(cells > 10000, `expected an exhaustive import (>10k cells), got ${cells}`);
  });

  await t.test('the schema file exists alongside (documentation contract)', () => {
    assert.ok(fs.existsSync(path.join(MONO, 'shared', 'schemas', 'external-mt-index.schema.json')));
  });
});
