/**
 * Integrity checks for the metric-reliability index
 * (shared/catalogue/metric-reliability.json) — the WMT meta-evaluation
 * artifact (master plan B3): correlations between automatic metrics and WMT
 * human judgments, per language pair, rolled up per target-language family.
 * Structural invariants only (the file is generated by
 * arena/scripts/import_wmt_metaeval.py, so a drift here means the importer
 * changed without this contract following):
 *
 *   - pinned, credited, champollion-derived provenance; the mutable data
 *     tarball must carry sha256 + ETag pins
 *   - license lane is non-commercial-hold (upstream data license unstated —
 *     founder review pending); flipping this requires touching this test
 *   - every cell's metric id resolves in shared/metric-registry.json (the
 *     metric-identity SSOT) and is declared in the artifact's metrics block
 *   - every cell's src/tgt resolves in the languages block; correlations stay
 *     in [-1, 1]; the family roll-up only counts preferred cells
 *
 * Skips when the index is absent (cli-only / packaged checkouts — the file is
 * monorepo-tracked and deliberately NOT bundled into the npm package).
 */

import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { validate } from '../scripts/lib/mini-schema.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MONO = path.resolve(__dirname, '..', '..');
const INDEX_FILE = path.join(MONO, 'shared', 'catalogue', 'metric-reliability.json');
const REGISTRY_FILE = path.join(MONO, 'shared', 'metric-registry.json');
const SCHEMA_FILE = path.join(MONO, 'shared', 'schemas', 'metric-reliability.schema.json');

const present = fs.existsSync(INDEX_FILE);

test('metric-reliability (WMT meta-eval derived index)', { skip: !present && 'index not present (cli-only checkout)' }, async (t) => {
  const idx = JSON.parse(fs.readFileSync(INDEX_FILE, 'utf8'));

  await t.test('carries pinned, credited, champollion-derived provenance', () => {
    assert.ok(idx.version >= 1);
    assert.equal(idx.provider, 'wmt-metrics-metaeval');
    assert.ok(Array.isArray(idx.sources) && idx.sources.length >= 2,
      'both upstreams (mt-metrics-eval + wmt-mqm-human-evaluation) must be pinned');
    for (const src of idx.sources) {
      assert.match(src.commit, /^[0-9a-f]{40}$/, `${src.name}: commit must be a full upstream SHA`);
      assert.match(src.retrieved, /^\d{4}-\d{2}-\d{2}$/);
      assert.ok(src.license, `${src.name}: upstream license posture must be recorded`);
      assert.ok(src.credit.length >= 10, `${src.name}: upstream credit must be recorded (always-cite-work)`);
    }
    const data = idx.sources.find((s) => s.data_url);
    assert.ok(data, 'the mutable data tarball source must be present');
    assert.match(data.data_sha256, /^[0-9a-f]{64}$/,
      'the tarball is not immutable — sha256 pin is mandatory');
    assert.ok(data.data_etag, 'ETag pin is mandatory');
    assert.match(idx.provenance, /champollion-derived/,
      'the correlations are a Champollion derivation and must say so');
    assert.match(idx.provenance, /derived from/,
      'provenance must name the upstreams');
  });

  await t.test('license lane stays non-commercial until founder review', () => {
    assert.equal(idx.license_lane.commercial_ok, false,
      'upstream data license is unstated — flipping this requires the founder license review AND updating this test');
    assert.ok(idx.license_lane.note.length >= 20);
  });

  await t.test('every cell metric resolves in the metric-identity SSOT', () => {
    const registry = JSON.parse(fs.readFileSync(REGISTRY_FILE, 'utf8'));
    const registryIds = new Set(Object.keys(registry.entries));
    const declared = new Set(Object.keys(idx.metrics));
    for (const id of declared) {
      assert.ok(registryIds.has(id),
        `metrics block id '${id}' is not a shared/metric-registry.json canonical id`);
    }
    for (const cell of idx.cells) {
      assert.ok(declared.has(cell.metric),
        `cell metric '${cell.metric}' missing from the metrics block`);
    }
  });

  await t.test('cells are sane: resolvable languages, in-range correlations', () => {
    assert.ok(idx.cells.length >= 500,
      `expected an exhaustive meta-eval import (>=500 cells), got ${idx.cells.length}`);
    for (const cell of idx.cells) {
      assert.match(cell.pair, /^[a-z]{2,3}-[a-z]{2,3}$/, `bad pair '${cell.pair}'`);
      assert.ok(idx.languages[cell.src], `src '${cell.src}' missing from languages`);
      assert.ok(idx.languages[cell.tgt], `tgt '${cell.tgt}' missing from languages`);
      assert.ok(['sys', 'seg'].includes(cell.level));
      assert.equal(typeof cell.computed, 'boolean');
      for (const k of ['pearson', 'spearman', 'kendall_tau_b']) {
        const v = cell[k];
        assert.ok(v === null || v === undefined || (v >= -1 && v <= 1),
          `${k}=${v} out of range on ${cell.testset}/${cell.pair}/${cell.metric}`);
      }
      if (cell.pairwise_accuracy != null) {
        assert.ok(cell.pairwise_accuracy >= 0 && cell.pairwise_accuracy <= 1);
      }
    }
  });

  await t.test('the low-resource lanes the import exists for are present', () => {
    const pairs = new Set(idx.cells.map((c) => c.pair));
    for (const p of ['en-gu', 'en-kk', 'en-iu', 'xh-zu', 'en-liv', 'sah-ru', 'en-bho', 'en-mas']) {
      assert.ok(pairs.has(p), `expected low-resource pair '${p}' in the index`);
    }
    // And the roll-up reaches beyond Indo-European.
    const families = Object.keys(idx.families);
    assert.ok(families.length >= 5,
      `expected >=5 target families, got ${families.length}: ${families.join(', ')}`);
  });

  await t.test('family roll-up counts preferred cells only', () => {
    let preferred = 0;
    const rolled = new Set();
    for (const cell of idx.cells) {
      if (cell.preferred) preferred += 1;
    }
    for (const fam of Object.values(idx.families)) {
      for (const perMetric of Object.values(fam.metrics)) {
        for (const level of Object.values(perMetric)) {
          for (const p of level.pairs) rolled.add(p);
          assert.ok(level.n_cells >= 1 && level.weight >= level.n_cells);
        }
      }
    }
    const preferredKeys = new Set(
      idx.cells.filter((c) => c.preferred).map((c) => `${c.testset}:${c.pair}`));
    for (const key of rolled) {
      assert.ok(preferredKeys.has(key), `rolled-up ${key} has no preferred cell`);
    }
    assert.equal(idx.counts.preferred_cells, preferred);
    assert.equal(idx.counts.cells, idx.cells.length);
  });

  await t.test('validates against its schema (vendored mini-schema)', () => {
    // mini-schema enforces type/required/enum/pattern/additionalProperties:false
    // etc.; the dynamic-keyed blocks (metrics/languages/families) are covered
    // by the structural assertions above.
    const schema = JSON.parse(fs.readFileSync(SCHEMA_FILE, 'utf8'));
    const { valid, errors } = validate(idx, schema);
    assert.ok(valid, `schema violations:\n${errors.slice(0, 10).join('\n')}`);
  });
});
