/**
 * Honesty guard for the homepage seam's metric-coverage data
 * (cli/website/src/data/metric-pops.json, generated by
 * cli/scripts/build-metric-pops.mjs). Every metric NAME the animation shows
 * must trace to a real SSOT metric, and the language-gating honesty rails must
 * hold: MQM (roadmap) never appears; AfriCOMET (African-only) never on the
 * generic float or the Andean card; the seal's metrics come from the sovereign
 * Cree card's own eval metrics; scores are flagged illustrative.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const readJSON = (p) => JSON.parse(readFileSync(join(HERE, p), 'utf8'));

const pops = readJSON('../website/src/data/metric-pops.json');
const registry = readJSON('../shared/metric-registry.json').entries;
const crk = readJSON('../shared/language-cards/crk.json');
const quz = readJSON('../shared/language-cards/quz.json');

test('metric-pops: float is non-empty and card/seal are present', () => {
  assert.ok(Array.isArray(pops.measureFloat) && pops.measureFloat.length >= 4);
  assert.ok(pops.card && pops.seal);
});

test('metric-pops: shown registry metrics exist; card hero is implemented', () => {
  const ids = [pops.card.hero.registryId, ...pops.card.concur.map((c) => c.registryId)];
  for (const id of ids) assert.ok(registry[id], `metric-registry has '${id}'`);
  assert.equal(registry[pops.card.hero.registryId].status, 'implemented');
});

test('metric-pops: MQM never appears (roadmap), AfriCOMET is gated', () => {
  const everyName = [
    ...pops.measureFloat,
    ...pops.card.concur.map((c) => c.name),
    ...pops.seal.names,
  ].join(' ');
  assert.doesNotMatch(everyName, /MQM/i, 'MQM is roadmap — never shown live');
  assert.doesNotMatch(pops.measureFloat.join(' '), /afri/i, 'AfriCOMET is African — not on the generic float');
  assert.doesNotMatch(pops.card.concur.map((c) => c.name).join(' '), /afri/i, 'AfriCOMET never on the Andean card');
});

test('metric-pops: card honesty is data-driven from the quz card', () => {
  assert.equal(pops.card.macroarea, quz.macroarea);
  assert.doesNotMatch(pops.card.macroarea, /afric/i, 'Cusco Quechua is not African — the AfriCOMET rail holds');
  assert.ok(pops.card.excludes && pops.card.excludes.AfriCOMET, 'the AfriCOMET exclusion + reason is recorded');
  assert.equal(pops.card.servicesCover, false, 'no service covers quz → the "fails direct" premise is true');
});

test('metric-pops: seal metrics come from the sovereign Cree card', () => {
  assert.equal(pops.seal.code, 'crk');
  for (const id of pops.seal.sourceMetrics) {
    // Gate 3: the eval wiring is OURS and moved to the config kernel; the
    // card no longer carries it. The seam's metric pops read the same kernel.
    const evalMetrics = crk.evalMetrics
      ?? readJSON('../../shared/catalogue/card-config.json').evalConfig?.crk?.evalMetrics;
    assert.ok(evalMetrics && evalMetrics[id], `crk.evalMetrics has '${id}'`);
  }
  assert.ok(pops.seal.names.length >= 2, 'the seal shows ≥2 morphology/FST names');
});

test('metric-pops: numeric scores are flagged illustrative', () => {
  assert.equal(pops.card.illustrative, true);
  assert.equal(pops.seal.illustrative, true);
});
