/**
 * contamination.mjs — how exposed a corpus is, computed from fetched signals.
 *
 * WHAT THIS REPLACES
 *   1,413 corpus cards carried a hand-written `contamination.risk` of LOW,
 *   MEDIUM or HIGH plus a paragraph of reasoning. 1,238 were generated by two
 *   bulk builders and 175 were written by a person. Neither kind is reproducible
 *   and neither can be checked, so both are archived rather than carried.
 *
 * WHAT IT CLAIMS, AND WHAT IT REFUSES TO CLAIM
 *   EXPOSURE, not membership. Proving a test set is inside a closed model's
 *   training data needs the training data or the model's internals, and we have
 *   neither. What metadata can support is how available the corpus has been to
 *   whoever built that model — which is the question Jacovi, Caciularu, Goldman
 *   & Goldberg, "Stop Uploading Test Data in Plain Text", EMNLP 2023
 *   (arXiv:2305.10160), is written around. Three of their mitigations invert
 *   directly into signals here.
 *
 * THE FIVE SIGNALS
 *   plainTextAvailable   Did our own fetcher get it without a token? Jacovi §1:
 *                        unencrypted public test data gets scraped.
 *   licenceAllowsDerivatives  A permissive licence means the corpus is re-hosted
 *                        elsewhere, and the mirrors get crawled too.
 *   sourceAndReferenceTogether  Jacovi §3: data published WITH its solution is
 *                        the worst case. Parallel corpora are inherently this.
 *   ageVsModelCutoffs    A corpus published after a model's cutoff cannot be in
 *                        it. Computable now that model release dates are fetched.
 *   webPresence          Common Crawl's CDX index — was this corpus's own
 *                        download URL crawled, and when.
 *
 * THE FAILURE MODE THAT SHAPES THIS FILE
 *   The CDX API has three outcomes, all observed against real corpus URLs:
 *
 *     crawled       github.com/openlanguagedata/flores → a capture, 2026-07-16
 *     not-captured  opus.nlpl.eu/GlobalVoices → "No Captures found"
 *     unknown       tatoeba.org → HTTP 504, on every retry
 *
 *   The third is the dangerous one, because the failure is ANTI-CORRELATED with
 *   the answer: the query times out on heavily-crawled hosts precisely BECAUSE
 *   they have so many captures. Treating a failed query as "not crawled" would
 *   systematically mark the most exposed corpora as the cleanest.
 *
 *   So an unknown signal can never lower the exposure. Where the unknowns could
 *   change the verdict, the verdict is `undetermined` and says which signal is
 *   missing. A number we cannot defend is worse than no number.
 */

/** Bumped when the RULES change, not when a corpus does. */
export const DERIVATION_VERSION = 'v1';

export const EXPOSURE = Object.freeze({
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  UNDETERMINED: 'undetermined',
});

export const WEB_PRESENCE = Object.freeze({
  CRAWLED: 'crawled',
  NOT_CAPTURED: 'not-captured',
  UNKNOWN: 'unknown',
});

/** Licences under which a corpus may legally be re-hosted, so mirrors exist. */
const PERMITS_REDISTRIBUTION = /^(CC0|CC-BY(-SA)?(-\d|$)|MIT|Apache|BSD|ODC|PDDL|Unicode)/i;
const NO_DERIVATIVES = /(-ND-|-ND$|NoDerivat)/i;

/**
 * @typedef {object} ContaminationInput
 * @property {boolean|null} plainTextAvailable   null when our fetcher never ran
 * @property {string|null} licence               SPDX or LicenseRef
 * @property {boolean|null} sourceAndReferenceTogether
 * @property {string|null} publishedDate         ISO date of the pinned release
 * @property {Array<{model: string, date: string}>} modelCutoffs
 * @property {{state: string, firstSeen?: string|null, lastSeen?: string|null,
 *             reason?: string|null}} webPresence
 */

/**
 * Score one corpus.
 *
 * @param {ContaminationInput} input
 * @returns {{exposure: string, signals: object[], because: string,
 *            unknowns: string[], derivationVersion: string,
 *            modelsPublishedAfter: string[]}}
 */
export function contaminationIndex(input) {
  const {
    plainTextAvailable = null,
    licence = null,
    sourceAndReferenceTogether = null,
    publishedDate = null,
    modelCutoffs = [],
    webPresence = { state: WEB_PRESENCE.UNKNOWN, reason: 'not queried' },
  } = input ?? {};

  const signals = [];
  const unknowns = [];

  // ── 1. Was it fetchable without a credential? ────────────────────────────
  if (plainTextAvailable === null) {
    unknowns.push('plainTextAvailable');
    signals.push({ signal: 'plainTextAvailable', value: null, raises: null });
  } else {
    signals.push({
      signal: 'plainTextAvailable',
      value: plainTextAvailable,
      raises: plainTextAvailable,
      why: plainTextAvailable
        ? 'we fetched it with no token, so anyone can'
        : 'the fetch needed a credential or the repo is gated',
    });
  }

  // ── 2. May it legally be re-hosted? ──────────────────────────────────────
  if (!licence) {
    unknowns.push('licence');
    signals.push({ signal: 'licenceAllowsDerivatives', value: null, raises: null });
  } else {
    const redistributable = PERMITS_REDISTRIBUTION.test(licence) && !NO_DERIVATIVES.test(licence);
    signals.push({
      signal: 'licenceAllowsDerivatives',
      value: redistributable,
      raises: redistributable,
      why: redistributable
        ? `${licence} permits redistribution, so mirrors exist and mirrors get crawled`
        : `${licence} restricts redistribution, so there are fewer copies to find`,
    });
  }

  // ── 3. Does it ship with its own answers? ────────────────────────────────
  if (sourceAndReferenceTogether === null) {
    unknowns.push('sourceAndReferenceTogether');
    signals.push({ signal: 'sourceAndReferenceTogether', value: null, raises: null });
  } else {
    signals.push({
      signal: 'sourceAndReferenceTogether',
      value: sourceAndReferenceTogether,
      raises: sourceAndReferenceTogether,
      why: sourceAndReferenceTogether
        ? 'source and reference are published together — Jacovi et al. §3, the worst case'
        : 'the reference side is held separately',
    });
  }

  // ── 4. Could it predate the models? ──────────────────────────────────────
  // ASYMMETRIC, deliberately. If every indexed model predates the corpus, none
  // can contain it and that settles the question outright. The converse does
  // NOT hold: that some model came later is not evidence of exposure, only the
  // absence of a temporal alibi, and counting it as a raising signal made a
  // gated, restrictively-licensed, separately-held corpus come out MEDIUM on
  // the strength of a model having been released. So age gates; it never raises.
  const publishedAfter = [];
  if (publishedDate && modelCutoffs.length) {
    for (const m of modelCutoffs) {
      if (m?.date && m.date >= publishedDate) publishedAfter.push(m.model);
    }
    signals.push({
      signal: 'ageVsModelCutoffs',
      value: publishedAfter.length,
      raises: false,
      why: publishedAfter.length
        ? `${publishedAfter.length} indexed model(s) postdate this corpus, so time does `
          + 'not rule out exposure — which is not the same as evidence of it'
        : 'every indexed model predates this corpus, so none can contain it',
    });
  } else {
    unknowns.push(publishedDate ? 'modelCutoffs' : 'publishedDate');
    signals.push({ signal: 'ageVsModelCutoffs', value: null, raises: null });
  }

  // ── 5. Is it on the open web? ────────────────────────────────────────────
  const web = webPresence?.state ?? WEB_PRESENCE.UNKNOWN;
  if (web === WEB_PRESENCE.UNKNOWN) {
    unknowns.push('webPresence');
    signals.push({
      signal: 'webPresence',
      value: null,
      raises: null,
      // Said plainly because the instinct is to read a failed query as a clean
      // result, and here that instinct is backwards.
      why: `not established (${webPresence?.reason ?? 'no reason recorded'}) — a failed `
        + 'CDX query is NOT evidence of absence; it times out most often on the '
        + 'heavily-crawled hosts, so the failure runs opposite to the answer',
    });
  } else {
    const crawled = web === WEB_PRESENCE.CRAWLED;
    signals.push({
      signal: 'webPresence',
      value: web,
      raises: crawled,
      why: crawled
        ? `Common Crawl holds a capture of its download URL${
          webPresence.firstSeen ? ` (first seen ${webPresence.firstSeen})` : ''}`
        : 'Common Crawl has no capture of its download URL',
    });
  }

  // ── Verdict ──────────────────────────────────────────────────────────────
  // Count only signals that actually spoke. An unknown never lowers exposure,
  // and where the unknowns could change the answer the answer is withheld.
  // Age is excluded from the count on both sides: it gates the verdict above
  // rather than voting in it, so leaving it in `spoke` would let a corpus reach
  // the three-signal threshold without three signals having actually spoken.
  const spoke = signals.filter((s) => s.raises !== null && s.signal !== 'ageVsModelCutoffs');
  const raising = spoke.filter((s) => s.raises).length;

  // If nothing can be in it, nothing else matters.
  const nothingCouldContainIt = publishedDate && modelCutoffs.length && !publishedAfter.length;
  if (nothingCouldContainIt) {
    return {
      exposure: EXPOSURE.LOW,
      signals,
      unknowns,
      modelsPublishedAfter: [],
      derivationVersion: DERIVATION_VERSION,
      because: 'every indexed model predates this corpus, so none of them can contain it, '
        + 'whatever its availability',
    };
  }

  let exposure;
  if (spoke.length < 3) {
    exposure = EXPOSURE.UNDETERMINED;
  } else if (raising >= 3) {
    exposure = EXPOSURE.HIGH;
  } else if (raising >= 1) {
    exposure = EXPOSURE.MEDIUM;
  } else {
    // Every signal that spoke says "not exposed" — but if an unknown remains
    // that could raise it, LOW would be a claim the evidence does not support.
    exposure = unknowns.length ? EXPOSURE.UNDETERMINED : EXPOSURE.LOW;
  }

  const because = exposure === EXPOSURE.UNDETERMINED
    ? `${spoke.length} of 5 signals established; ${unknowns.join(', ')} unknown — `
      + 'reporting a level here would rest on signals we do not have'
    : `${raising} of ${spoke.length} established signals raise exposure`
      + (unknowns.length ? ` (${unknowns.join(', ')} unknown, which can only raise it further)` : '');

  return {
    exposure,
    signals,
    unknowns,
    modelsPublishedAfter: publishedAfter,
    derivationVersion: DERIVATION_VERSION,
    because,
  };
}
