#!/usr/bin/env python3
"""Generate the complete-inventory section of ``docs/INDEX.md``.

The hub stopped being updated around 2026-07-12 and 41 documents — including
the canonical homepage plan, the canonical nav spec and a founder-signed-off
trust model already live on production — became invisible to it.  A
hand-maintained list of 143 files is the same anti-pattern as a hardcoded
display value: it is correct on the day it is written and wrong forever after.

So the inventory is generated and the *judgment* is hand-written.  Everything
between the BEGIN/END markers in ``docs/INDEX.md`` is owned by this script;
everything above them (Start Here, the lanes, the orientation) is human-owned
and never touched.

Usage:
    python3 scripts/build_docs_index.py            # rewrite the section
    python3 scripts/build_docs_index.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "INDEX.md"

BEGIN = "<!-- BEGIN GENERATED INVENTORY -->"
END = "<!-- END GENERATED INVENTORY -->"

# Order matters: this is the order sections appear in the rendered hub.
STATUS_SECTIONS = [
    ("current", "Current", "How things work today. Trust these and act on them."),
    (
        "record",
        "Records",
        "True when written — dated audits, reviews, verifications, decision "
        "briefs and event prep. Authoritative about **what happened**, and "
        "often the only surviving account of a founder decision. Never a "
        "description of the present: re-check any instruction against the code.",
    ),
    (
        "needs-review",
        "Awaiting a decision",
        "Open questions blocking work. These need a founder ruling.",
    ),
    ("draft", "Drafts", "In progress, not yet load-bearing."),
]

FOLDER_LABELS = {
    ".": "Root",
    "audit": "audit/",
    "brand": "brand/",
    "design": "design/",
    "dogfood": "dogfood/",
    "funding": "funding/",
    "governance": "governance/",
    "grants": "grants/",
    "legacy-ci-cd": "legacy-ci-cd/",
    "marketplace": "marketplace/",
    "thesis": "thesis/",
}


def frontmatter_status(text: str) -> str | None:
    match = re.search(r"^status:\s*(\S+)", text[:600], re.M)
    return match.group(1) if match else None


def title_of(path: Path, text: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, re.M)
    if match:
        return match.group(1).strip()
    return path.stem


def collect() -> dict[str, list[tuple[str, Path, str]]]:
    """Return {status: [(folder, path, title), ...]}."""
    buckets: dict[str, list[tuple[str, Path, str]]] = {}
    for path in sorted(DOCS.rglob("*.md")):
        if "node_modules" in path.parts:
            continue
        rel = path.relative_to(DOCS)
        if rel.parts[0] == "archive" or rel.name == "INDEX.md":
            continue
        text = path.read_text(encoding="utf-8")
        status = frontmatter_status(text) or "current"
        folder = str(rel.parent)
        buckets.setdefault(status, []).append((folder, rel, title_of(path, text)))
    return buckets


def render() -> str:
    buckets = collect()
    total = sum(len(v) for v in buckets.values())
    archived = sum(
        1
        for p in (DOCS / "archive").rglob("*.md")
        if "node_modules" not in p.parts and p.name != "README.md"
    )

    out: list[str] = [
        BEGIN,
        "",
        "## Complete inventory",
        "",
        f"*Generated by `scripts/build_docs_index.py` — {total} live documents, "
        f"plus {archived} in [`archive/`](archive/README.md). Do not hand-edit "
        f"below this line; run the script. The curated entry points above are "
        f"human-written and are not touched by it.*",
        "",
    ]

    for status, heading, blurb in STATUS_SECTIONS:
        entries = buckets.get(status, [])
        if not entries:
            continue
        out.append(f"### {heading} — `status: {status}` ({len(entries)})")
        out.append("")
        out.append(blurb)
        out.append("")
        by_folder: dict[str, list[tuple[Path, str]]] = {}
        for folder, rel, title in entries:
            by_folder.setdefault(folder, []).append((rel, title))
        for folder in sorted(by_folder, key=lambda f: (f != ".", f)):
            if len(by_folder) > 1:
                out.append(f"**{FOLDER_LABELS.get(folder, folder + '/')}**")
                out.append("")
            for rel, title in sorted(by_folder[folder]):
                out.append(f"- [{rel}]({rel}) — {title}")
            out.append("")

    # Anything with a status we do not section above would silently vanish.
    unknown = set(buckets) - {s for s, _, _ in STATUS_SECTIONS}
    for status in sorted(unknown):
        out.append(f"### Unsectioned — `status: {status}` ({len(buckets[status])})")
        out.append("")
        for _, rel, title in sorted(buckets[status], key=lambda e: e[1]):
            out.append(f"- [{rel}]({rel}) — {title}")
        out.append("")

    out.append(END)
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    text = INDEX.read_text(encoding="utf-8")
    section = render()

    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        stop = text.index(END) + len(END)
        updated = text[:start] + section + text[stop:]
    else:
        updated = text.rstrip() + "\n\n---\n\n" + section + "\n"

    if check:
        if updated != text:
            print(
                "docs/INDEX.md inventory is stale — run "
                "`python3 scripts/build_docs_index.py`",
                file=sys.stderr,
            )
            return 1
        print("docs/INDEX.md inventory is up to date")
        return 0

    INDEX.write_text(updated, encoding="utf-8")
    print(f"docs/INDEX.md inventory regenerated ({section.count(chr(10) + '- ')} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
